### ISSUE TITLE
wrong response model in swagger when two classes have the same name but different namespace

### ISSUE THREAD

**Issue by figuerres** [rbeauchamp/Swashbuckle.OData#100]
So I have a large project that has an EF table Locations  with rows of type Location in my company.data.model namespace.
but the Google API for Geocoding has a class called Location in a different namespace like Company.Web.Providers.Google

all of the Odata works correctly, the namespaces bind the right classes and we get the right result Json data.
but the swagger page lists the model of the google class and not the model of the EF / Odata class.
I am not sure how to resolve this.
I need the google class to work with rest calls that map the json into the clr class where I do the geocoding. i'd rather not mess with the json mapping there.
.Net see the namespaces and is happy.

possibly the generated swagger json file needs to prefix the namespace into the model name to make them distinct ??

**Comment by rbeauchamp-lendingtree** [comment]
hey @figuerres, give this a try https://github.com/domaindrivendev/Swashbuckle#usefulltypenamesinschemaids

**Comment by figuerres** [comment]
Thanks!   that looks like what i needed!  first glance it appears to solve the issue!
