### ISSUE TITLE
data type not shown in swagger for  DbGeography in sql server

### ISSUE THREAD

**Issue by figuerres** [rbeauchamp/Swashbuckle.OData#102]
my data model has the sql server / .net  DbGeography  type and the data returns in the json just fine but I guess the Odata plugin is skipping it ??
or is this an issue with Swashbuckle not handling it ?

**Comment by rbeauchamp** [comment]
Supporting this would be an enhancement.

**Comment by rbeauchamp** [comment]
Closing this old feature request as it is not important enough for someone to spend the time to implement it.
