### ISSUE TITLE
Cannot use self build dll

### ISSUE THREAD

**Issue by lautarobock** [rbeauchamp/Swashbuckle.OData#107]
I download the project and downgrade `system.webapi` version to 5.2.2 (because my project use this and you fix to 5.2.3).
Then build from visual studio. Then Copy `Swashbuckle.OData.dll` to my project and add to references. 
Build my proyect and when i try to see documentation 

> {"message":"An error has occurred.","exceptionMessage":"Could not load file or assembly 'Swashbuckle.OData, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required

,

**Comment by lautarobock** [comment]
solved

**Comment by renatoleite** [comment]
Hello, how do you solved it?? I have the same issue. The copy to local of this reference is set to true, but the VS is not copying the assembly. I don't no why.

**Comment by lautarobock** [comment]
I've create a fork, replace some dependencies and downlgrade the version
https://github.com/lautarobock/Swashbuckle.OData
