### ISSUE TITLE
ODataActionParameters required for Actions

### ISSUE THREAD

**Issue by vantubbe** [rbeauchamp/Swashbuckle.OData#112]
I get the following error when I have a post endpoint without ODataActionParameters.

Assumption failed: odataActionParametersDescriptor != null"

Works:

```
[HttpPost]      
public IHttpActionResult TestMethod(int rootTenantId, ODataActionParameters parameters)
```

Does not work:

```
[HttpPost]      
public IHttpActionResult TestMethod(int rootTenantId)

```

**Comment by rbeauchamp** [comment]
Is that a message generated by Swashbuckle.OData or the MS OData infrastructure?

**Comment by PavelPikat** [comment]
👍 Having the same issue

@vantubbe Did you get around it?

**Comment by vantubbe** [comment]
Yes, the best way is to add ODataActionParameter to the action signature, even if you're not going to use it. It can also be fussy about nullable types in the signature, I usually can remove them as a work around.

Mike

**Comment by corveen** [comment]
How can I add ODataActionParameters to the action signature without breaking OData parameter binding?
I get this exception
System.InvalidOperationException: 'Can't bind multiple parameters ('request' and 'parameters') to the request's content.'

Method signature:
`[HttpPost]
		[ODataRoute("TransactionExecute")]
		[ODataRoute("Accounts({key})/TransactionsNamespace.TransactionExecute")]
		public IHttpActionResult ExecuteOnEntitySet([FromUri] string key, [FromBody]TransactionExecuteRequest request, ODataActionParameters parameters) `
