### ISSUE TITLE
Migration to ODL 7.0.0 and WebApi.OData 6.0.0

### ISSUE THREAD

**Issue by patrickmichalina** [rbeauchamp/Swashbuckle.OData#114]
Right now this project works fine in pre-6.0.0 land. But with the drop of version 6 from the Web Api team we see updated performance across the board in the OData pipeline. It also fixes a number of bugs such as the infamous 500 error when a SingleResult not found should return 404.

I loaded the project to begin an update but found issues when running in visual studio 2015. I would like to contribute but if it means not doing so in VS 2015 (without warnings), then I will have to fork and start my work there and diverge. Also, why is the Nuget package included in source? I don't think want to know what your take is on this before I start the migration.

Thanks

**Comment by rbeauchamp** [comment]
Hi @patrickmichalina 

Thanks for proposing to work on this. Did you have a question about VS 2015? Should run fine, that's what I use for development. What issues are you having?

Also, where are you seeing a NuGet package included in the source?

If you are referring to: 

https://github.com/rbeauchamp/Swashbuckle.OData/tree/master/Swashbuckle.OData.NuGetPackage

this is a project type that **generates** a NuGet package for uploading to nuget.org, it is not a NuGet package itself.

**Comment by 0xced** [comment]
I started working on it and should have pull request ready very soon.

**Comment by 0xced** [comment]
I submitted #115 for review. And there's a lot to review. 😉

**Comment by patrickmichalina** [comment]
Oh wow. That was quick. Thanks for getting it done!

**Comment by patrickmichalina** [comment]
@rbeauchamp To clarify about my original post, when loading vanilla VS 2015, the Nuget project type doesn't load and remains in the "unloaded" state. I take it you don't have a deployment task set on the server to output a and publish the nuget package? NuGet,exe does this pretty well when loading from the .csproj.

**Comment by rbeauchamp-lendingtree** [comment]
I leverage [NuGet Package Project](https://visualstudiogallery.msdn.microsoft.com/fbe9b9b8-34ae-47b5-a751-cb71a16f7e96) to generate the NuGet package. I've now added a link to that in the Development section of the README. Thanks.

**Comment by rbeauchamp** [comment]
Hey @patrickmichalina and @0xced: do you actually want the dependency constraints currently defined in the packages.config?:

![image](https://cloud.githubusercontent.com/assets/471149/19734866/175f0548-9b5e-11e6-8791-2751fc26bc31.png)

**Comment by 0xced** [comment]
As I said in #115:
> Also, I'm not yet familiar enough with Windows dll dependencies, so maybe I got the packages.config (allowedVersions) and Web.config (bindingRedirect) wrong.

And indeed it was wrong! I opened #116 to address the dependencies' requirements.

**Comment by rbeauchamp** [comment]
Updates are now available via NuGet: https://www.nuget.org/packages/Swashbuckle.OData/3.0.0
