### ISSUE TITLE
Unable to find a version 'Microsoft.AspNet.OData' that is compatible with 'Swashbuckle.OData 2.19.0 constraint: Microsoft.AspNet.OData (< 6.0.0)'

### ISSUE THREAD

**Issue by PremeraSOAPOC** [rbeauchamp/Swashbuckle.OData#117]
I have Microsoft.AspNet.Odata v5.9.1. However when I install Swashbuckle.Odata 2.19, it shows an incompatible error.

**Comment by patrickmichalina** [comment]
You probably want to skip 2.19.0 for now and rollback to 2.18.0. 

once 3.0.0 is released you should be good to go again.

**Comment by rbeauchamp** [comment]
v3.0.0 is now available on NuGet: https://www.nuget.org/packages/Swashbuckle.OData/3.0.0

@PremeraSOAPOC Closing this issue for now. Let us know if you still have issues.
