### ISSUE TITLE
Getting Error trying to get Swagger working

### ISSUE THREAD

**Issue by kklauder** [rbeauchamp/Swashbuckle.OData#119]
Hello,

Getting Error:

VS2015 
Swashbuckle 5.3.2
Swashbuckle.OData 2.18.3

Please Help

Thanks

-Ken

500 : {"Message":"An error has occurred.","ExceptionMessage":"Assumption failed: odataActionParametersDescriptor != null","ExceptionType":"System.Diagnostics.Contracts.__ContractsRuntime+ContractException","StackTrace":" at System.Diagnostics.Contracts.__ContractsRuntime.TriggerFailure(ContractFailureKind kind, String msg, String userMessage, String conditionTxt, Exception inner)\r\n at System.Diagnostics.Contracts.__ContractsRuntime.ReportFailure(ContractFailureKind kind, String msg, String conditionTxt, Exception inner)\r\n at System.Diagnostics.Contracts.__ContractsRuntime.Assume(Boolean condition, String msg, String conditionTxt)\r\n at Swashbuckle.OData.Descriptions.MapToODataActionParameter.Map(Parameter swaggerParameter, Int32 parameterIndex, HttpActionDescriptor actionDescriptor)\r\n at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.<>c__DisplayClass5_0.<GetHttpParameterDescriptor>b__0(IParameterMapper mapper)\r\n at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()\r\n at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.GetHttpParameterDescriptor(Parameter parameter, Int32 index, HttpActionDescriptor actionDescriptor)\r\n at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.GetParameterDescription(Parameter parameter, Int32 index, HttpActionDescriptor actionDescriptor)\r\n at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.<>c__DisplayClass3_0.<CreateParameterDescriptions>b__0(Parameter parameter, Int32 index)\r\n at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()\r\n at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()\r\n at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()\r\n at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.CreateParameterDescriptions(Operation operation, HttpActionDescriptor actionDescriptor)\r\n at Swashbuckle.OData.Descriptions.SwaggerOperationMapper.Map(ODataActionDescriptor oDataActionDescriptor)\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.<>c__DisplayClass7_0.<GetApiDescriptions>b__2(IODataActionDescriptorMapper mapper)\r\n at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()\r\n at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.<GetApiDescriptions>b__7_1(ODataActionDescriptor oDataActionDescriptor)\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n at Swashbuckle.OData.CollectionExtentions.ToCollection[T](IEnumerable`1 source)\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions()\r\n at System.Lazy`1.CreateValue()\r\n at System.Lazy`1.LazyInitValue()\r\n at System.Lazy`1.get_Value()\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.get_ApiDescriptions()\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"} http://localhost:56470/swagger/docs/v1

**Comment by weltmeyer** [comment]
i get the same error when calling /docs/v1
Swashbuckle.Core: 5.3.2
Swashbuckle.Odata: 3.0.0



 ```
config
                .EnableSwagger(c => {
                    c.SingleApiVersion("v1", "A title for your API");
                    c.CustomProvider(defaultProvider => new ODataSwaggerProvider(defaultProvider, c, GlobalConfiguration.Configuration));
                }

                )
                .EnableSwaggerUi();
```

**Comment by 0xced** [comment]
This looks like a duplicate of #86. (Problem with asserting odataActionParametersDescriptor != null)

**Comment by kklauder** [comment]
I did have an action on my OData service...

var action = res.Action("APPROVE");

Once I took the action out swagger then worked.
