### ISSUE TITLE
Swashbuckle.oData 3.0.0 - Microsoft.Extensions.DependencyInjection  

### ISSUE THREAD

**Issue by glyons** [rbeauchamp/Swashbuckle.OData#120]
Maybe I'm missing something here,  v3.0.0 depends on Microsoft.Extensions.DependencyInjection  and  Microsoft.AspNet.oData 6.0.0. However these nugets  seem to be targetted for .NETStandard 1.0.  So unable to update Swashbuckle.oData from 2.18.8 to 3.0.0.

  Install failed. Rolling back...
update-package : Could not install package 'Microsoft.Extensions.DependencyInjection 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but 
the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ update-package Microsoft.AspNet.oData
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand
 
Any ideas, thanks, Gavin

**Comment by rbeauchamp** [comment]
@glyons this project will not support .net core any time soon. my guess is that a new project will need to be written from scratch...
