### ISSUE TITLE
Limit HTTP Methods

### ISSUE THREAD

**Issue by antoniogarcez** [rbeauchamp/Swashbuckle.OData#121]
Hi,

To generate documentation, Swashbuckle.OData creates a request for each HTTP method (GET, POST, PUT, DELETE...) but I only need GET. 

How can I restrict created requests?

**Comment by thechadc** [comment]
not make those methods public?

**Comment by antoniogarcez** [comment]
I put a filter on Swashbuckle and it's solved my problem.
