### ISSUE TITLE
Update NuGet package to support latest Swashbuckle.Core (5.5.3)

### ISSUE THREAD

**Issue by PavelPikat** [rbeauchamp/Swashbuckle.OData#125]
Currently, Sashbuckle.OData NuGet package is locked to <Swashbuckle.Core 5.4.0, and the latest version of Core is 5.5.3.
Is it because there are breaking changes in 5.5.3 or any other blocking issues? Can OData package work with latest Core?

**Comment by rbeauchamp** [comment]
Hi Pavel, I think that's something you'll have to investigate to get an answer. Feel free to submit a pull request with the updates.

**Comment by PavelPikat** [comment]
@rbeauchamp Yeah, sorry I rushed creating the issue without first spotting this one: 
https://github.com/rbeauchamp/Swashbuckle.OData/issues/68
I guess I'll have to stick to working versions combo for now
