### ISSUE TITLE
EnsureUnique OperationFilter prevents users config 

### ISSUE THREAD

**Issue by joshbooker** [rbeauchamp/Swashbuckle.OData#126]
The Document Filter to ensure unique OperationIDs is helpful in some cases, but what if we don't want them to be unique? The problem with having a document filter in your code, is it cannot be overridden in SwaggerConfig.cs user code. 

I believe the doc filter happens after all the other filters in user code. I believe it would be better practice to ensure users have full capabilities of swashbuckle's configuration options. If they want unique then they can add an operation filter in user code. Thanks again.

Related commit:
https://github.com/rbeauchamp/Swashbuckle.OData/commit/1d51c181185b5a2f07591151cfe2d0187f0208be

Related Issue:
https://github.com/rbeauchamp/Swashbuckle.OData/issues/9

**Comment by rbeauchamp** [comment]
hi josh, happy new year to you. Care to submit a pull request with unit tests for this?

**Comment by joshbooker** [comment]
Thanks for your reply. Afraid I lack the skills to do a proper PR. 
Just wish this was optional or nonexistent since the same can be achieved optionally in user code. https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/EnsureUniqueOperationIdsFilter.cs
