### ISSUE TITLE
Swashbuckle.OData.dll does not represent a strongly named assembly

### ISSUE THREAD

**Issue by icnocop** [rbeauchamp/Swashbuckle.OData#127]
Hi.

Thank you for Swashbuckle.OData.dll.

If my project is configured so the output assembly is signed with a strong name, it will require referenced assemblies to also be signed with a strong name key.
However, since Swashbuckle.OData.dll is not, I get the following compiler error:
`error CS8002: Referenced assembly 'Swashbuckle.OData, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

I installed Swashbuckle.OData.dll 3.0.0 from NuGet.

Thank you.

**Comment by lengly** [comment]
same issue

**Comment by rbeauchamp** [comment]
Can you please submit a PR where the DLLs are signed with a strong name?

**Comment by cibergarri** [comment]
Richard, my current PR has them.

Obtener Outlook para Android<https://aka.ms/ghei36>


________________________________

**Comment by rbeauchamp** [comment]
Fixed in https://github.com/rbeauchamp/Swashbuckle.OData/releases/tag/v3.2.0. NuGet package: https://www.nuget.org/packages/Swashbuckle.OData/3.2.0 Thanks @cibergarri!
