### ISSUE TITLE
Support 5.5.X of Swashbuckle

### ISSUE THREAD

**Issue by Vaccano** [rbeauchamp/Swashbuckle.OData#128]
The current version of Swashbuckle.OData that is on nuget onlye allows Swashbuckle versions that are below 5.4.0.  

Swashbuckle is up to version 5.5.3, so if I want to use the latest version of Swashbuckle, I can't use Swashbuckle.OData.  And that is sad, because it looks awesome!

Please consider updating to support the latest version of Swashbuckle.

**Comment by rbeauchamp** [comment]
Fix for this is available on NuGet: https://www.nuget.org/packages/Swashbuckle.OData/3.1.0

Thanks for your work @cibergarri !
