### ISSUE TITLE
License file incomplete

### ISSUE THREAD

**Issue by ipvalverde** [rbeauchamp/Swashbuckle.OData#130]
The license file seems to be incomplete. It also states that "certain portions" of the code is distributed as copyrighted code from author (@rbeauchamp, I believe).

I couldn't find any mention about changes in your copyrighted code.

I would like to use your library in an existing application, but we use the Newtonsoft.Json version 6.x, but Swashbuckle.OData uses the version 7.x. The fastest solution for my scenario is to downgrade the Newtonsoft.Json of Swashbuckle.OData to version 6.
If I do that and redistribute the resulting binaries with my product, do I need to make this change open-source?

**Comment by rbeauchamp** [comment]
Hi @ipvalverde, do the changes made by @cibergarri meet your need: can we close this issue?

See https://github.com/rbeauchamp/Swashbuckle.OData/commit/072d056bfa0009769a1241485ecbe13773435fdc#diff-dc5cde275269b574b34b1204b9221cb2 which is now included in release v3.2.0. https://www.nuget.org/packages/Swashbuckle.OData/3.2.0

**Comment by rbeauchamp** [comment]
@ipvalverde In response to your question: "If I do that and redistribute the resulting binaries with my product, do I need to make this change open-source?"

I'm not a lawyer, but the license is basically the MIT license which allows re-distributions without requiring that you open-source your modifications. you do need to retain/propagate certain notices specified in the license, though.

**Comment by ipvalverde** [comment]
Hi @rbeauchamp . That change you mentioned actually solves my problem, thank you.

And thanks for the changes @cibergarri .
