### ISSUE TITLE
Swashbuckle.OData brings in a lot of unnecessary NuGets

### ISSUE THREAD

**Issue by alexandery** [rbeauchamp/Swashbuckle.OData#137]
Due to the use of Flurl library, Shawshbuckle.Odata brings in tens of .NETStandard nugets packages. My projects explode with close to 30-40 extra packages that I do not need otherwise, but they all get dragged along for Flurl. And all of this for some basic functionality that is only needed in two classes.

Any chance Flurl can be removed and replaced with custom code?

**Comment by rbeauchamp** [comment]
yes, good idea. can you make the changes and submit a PR?

**Comment by rbeauchamp** [comment]
Thank you @alexandery for replacing Flurl with custom code!

Your latest changes are now available in v3.2.1: https://www.nuget.org/packages/Swashbuckle.OData/3.2.1
