### ISSUE TITLE
Swagger 2.0 with API 2.o and Odata 3.0

### ISSUE THREAD

**Issue by lvalinho** [rbeauchamp/Swashbuckle.OData#142]
Hello,
My team writed a question in stackoverflow about swashbuckle.odata on but no one answer yet. (http://stackoverflow.com/questions/43787666/swagger-2-0-with-api-2-o-and-odata-3-0)

Here's the copy of the problem description:

I been trying to implement swagger, through [Swashbuckle][1] on my application, but i get no endpoints at all on my swagger ui, and my doc just returns this:

`{
 "swagger": "2.0",
  "info": {
     "version": "v1",
     "title": "Glose.EAM.WebAPI.V4"
  },
  "host": "localhost:24320",
  "schemes": [
     "http"
   ],
  "paths": {},
  "definitions": {}
}`

In my webApiConfig i set the following configuration from following the dummys
var swagConfig = new HttpSelfHostConfiguration("http://localhost:24320");

`SwaggerConfig.Register();
WebApiConfig.Register(swagConfig);

using (var server = new HttpSelfHostServer(swagConfig))
{
     server.OpenAsync().Wait();
}`

My swagger configuration is the standart one created by Swashbuckle:
` GlobalConfiguration.Configuration 
.EnableSwagger(c =>
{                       
    c.SingleApiVersion("v1", "NB.EAM.WebAPI.Odata");

    var baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
    var commentsFileName = Assembly.GetExecutingAssembly().GetName().Name + ".XML";
    var commentsFile = Path.Combine(baseDirectory, "bin", commentsFileName);
    c.IncludeXmlComments(commentsFile);

    c.DocumentFilter<ApplyResourceDocumentation>();

    c.CustomProvider(defaultProvider => new ODataSwaggerProvider(defaultProvider, c, GlobalConfiguration.Configuration).Configure(odataConfig =>
    {

        odataConfig.IncludeNavigationProperties();
    }));
})
.EnableSwaggerUi(c =>
{                        
});`

Any idea what i might be missing?

Thank you.

**Comment by cibergarri** [comment]
I have answered in the stackoverflow thread.

**Comment by lvalinho** [comment]
Thank you for your answer. 
We added more information on stackoverflow (http://stackoverflow.com/questions/43787666/swagger-2-0-with-api-2-o-and-odata-3-0). 
We tried lot of things, but unfortunately we are not succeed putting api with odata working with swagger.
