### ISSUE TITLE
Running Swashbuckle.OData in VS 2017 - IISExpress.exe - Precondition failed

### ISSUE THREAD

**Issue by rohitiscancerian** [rbeauchamp/Swashbuckle.OData#143]
![image](https://cloud.githubusercontent.com/assets/13632788/26312633/22788da0-3f00-11e7-8433-888e4a5859ed.png)

**Comment by carand315** [comment]
I Solved it this:
- Install Code Contracts
- Remove word CONTRACTS_FULL from conditional compilation symbols in Build project settings.

**Comment by rohitiscancerian** [comment]
https://marketplace.visualstudio.com/items?itemName=RiSEResearchinSoftwareEngineering.CodeContractsforNET

This does not supports VS 2017 . Do  you have the compatible one ?
