### ISSUE TITLE
Incorrect specifications for global actions and functions

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [rbeauchamp/Swashbuckle.OData#145]
The following global _action_ definition:
```csharp
var action = builder
    .Action("RegisterEmployee")
    .ReturnsFromEntitySet<Employee>("Employees");

action.Parameter<string>("UserEmail");
action.Parameter<string>("EmployeeEmail");
```
results in two separate parameters instead of the expected body parameter:

![odata-action](https://cloud.githubusercontent.com/assets/1670232/26579472/4ca0d09e-4534-11e7-82b0-0e114206b36c.png)

---

The following global _function_ definition:
```csharp
var function = builder
    .Function("GetEmployeeForRegistration")
    .ReturnsFromEntitySet<Employee>("Employees");

function.Parameter<string>("UserEmail");
function.Parameter<string>("EmployeeEmail");
```
gives two operations instead of one:

![odata-function](https://cloud.githubusercontent.com/assets/1670232/26579483/5a8760a6-4534-11e7-9840-27ac3017c55a.png)

**Comment by cibergarri** [comment]
Hi Jaap!

Could it be caused because you have a ODataRoute placed in the method?? Try to remove it, it should work anyway.

Regards.
