### ISSUE TITLE
Output doesn't support $apply

### ISSUE THREAD

**Issue by robertmclaws** [rbeauchamp/Swashbuckle.OData#147]
The OData v4 specification [allows for a query aggregation method called $apply](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html#_Toc378326289). In the generated output for this library, the $apply option is not present on GET methods, as seen in the following screenshot: 

![image](https://cloud.githubusercontent.com/assets/1657085/26588743/30601dc8-4524-11e7-85f7-a3b552a4cdda.png)

Would be great if this option could be added in, as we use it for grouping a LOT.

Thanks!

**Comment by rbeauchamp** [comment]
Moved to #150
