### ISSUE TITLE
Support Rest and OData API Mix?

### ISSUE THREAD

**Issue by aaronwjha** [rbeauchamp/Swashbuckle.OData#15]
I have an API that combines both ApiController and ODataController in a single app. Adding the ODataSwaggerProvider properly documents the OData calls, but hides the documentation for the REST calls. Is this a known issue? Is there a workaround?

**Comment by rbeauchamp-lendingtree** [comment]
Hi @aaronwjha, yes, this is a known issue with no workaround yet. I'm labeling this as an enhancement and will include in an upcoming release. Thanks.

**Comment by rbeauchamp-lendingtree** [comment]
Hi @aaronwjha, this is now available in v2.4.0. Please let me know if you find any issues.

**Comment by aaronwjha** [comment]
Works perfectly. Thanks a ton!

**Comment by rbeauchamp** [comment]
Nice!
