### ISSUE TITLE
Swashbuckle.OData  support .net core ???

### ISSUE THREAD

**Issue by a764578566** [rbeauchamp/Swashbuckle.OData#154]

**Comment by rbeauchamp** [comment]
No, because as far as I know ASP.NET core does not yet support OData.

**Comment by a764578566** [comment]
OK， Thank for you

**Comment by ysmoradi** [comment]
I've managed to run Microsoft.AspNet.OData 6.0 (The version you're using in ASP.NET/Katana projects) in ASP.NET Core 2.0. It works fine on both .NET Full and .NET Core, but this project (Swashbuckle.OData) needs a few steps to be compatible.

We've to remove dependency to System.ServiceModel, some usages can be replaced using System.ServiceModel.Primitives, but following usages of UriTemplate can not be ported anyway.

https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/Descriptions/OperationExtensions.cs#L30
https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/Descriptions/ODataSwaggerUtilities.cs#L65-L70

It's a good idea to use https://github.com/tavis-software/Tavis.UriTemplates instead of System.ServiceModel in those codes. I'm creating a new PR to be submitted to this project.

After that we can target both .NET Standard 2 and .NET 4.5.2 ( The current version of .NET framework being used in Swashbuckle.OData).

Note that nothing can stops you from using asp.net core with full .net framework today, even this project works without any modification. Your app's overall performance will be boosted at least and you can leverage exciting ASP.NET Core middlewares in your app too. To get more details read the docs on https://docs.bit-framework.com/ .NET Core support will be added to that framework in near future and you can leverage that without any code modification in your app. (We've ported Signalr, Web API and OData, only a few steps are remaining)

**Comment by travnik** [comment]
Whether there will be a support Swashbuckle.OData for the platform a .net core 2.0?

**Comment by eloekset** [comment]
I'm using Microsoft.AspNetCore.OData 7.0.0-beta1, ref: https://github.com/OData/WebApi/issues/939.
I'm able to create an OData API along with an existing ASP.NET Core API and query an entity. However it breaks the Swagger document: 

*InvalidOperationException: No media types found in &#x27;Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes&#x27;. Add at least one media type to the list of supported media types.*

I can't register the ODataSwaggerProvider like documented for ASP.NET WebAPI, since the ASP.NET Core IApplicationBuilder requires another implementation.
![image](https://user-images.githubusercontent.com/791721/35097085-ef1393d0-fc4e-11e7-9991-fbb999386dfc.png)

**Comment by davidhjones** [comment]
Now that [AspNetCore.OData beta2](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/) has been released, what is the plan for Swashbuckle.OData support on AspNetCore? The OData library seems to be far enough along to pick back up on Swashbuckle.OData support. @rbeauchamp is there a plan for Swashbuckle.OData support on Core?

**Comment by souchprod** [comment]
+1

**Comment by jouz3** [comment]
+1

**Comment by davidhjones** [comment]
@rbeauchamp any update?

**Comment by nmg196** [comment]
+1

**Comment by mburnham** [comment]
+1

**Comment by RodionPronin** [comment]
+1

**Comment by SamiMajed** [comment]
We're also using NetCore.App with OData successfully and would like to use Swagger. 

Has support been added?  

If so, which swagger nuget packages would we use for the below combination? 
[.NetCore.App + Microsoft.AspNetCore.OData]

**Comment by viniciusmiguel** [comment]
+1

**Comment by reinoboonstra** [comment]
+1

**Comment by wally666** [comment]
+1

**Comment by ICodeGorilla** [comment]
+1

**Comment by patricknolan** [comment]
+1

**Comment by sumit4palz** [comment]
I started with Swagger than later we had to use Odata. Now Swagger is broken.  Any alternatives or workaround?

**Comment by tntwist** [comment]
+1

**Comment by felipecrestani** [comment]
+1 Please!!!!!!!!!!!!!!!!!!!!

**Comment by TomaszSt** [comment]
+1

**Comment by Ka-Marius** [comment]
+1

**Comment by maximpashuk** [comment]
I have some workaround:

- you can add odata before aspnet mvc
``` csharp
        public static IApplicationBuilder UseODataMvc(this IApplicationBuilder app, Action<IRouteBuilder> setupAction)
        {
            return app
                .UseODataBatching()
                .UseRouter(builder =>
            {
                builder.DefaultHandler = app.ApplicationServices.GetRequiredService<MvcRouteHandler>();
                setupAction(builder);
            });
        }
```
later call in Configure() method
```
                x.UseODataMvc()
                    .UseMvc()

```

So your odata controllers will hit BEFORE any mvc controllers.
So you can have documentation-only controllers, which will never be hit at all.

Controller1 : ODataController - doing all things, has no swagger-related attributes
Controller1Doc : ControllerBase - mapped to same route, has all swagger stuff, never be hit by aspnetcore, but providing metadata for swagger.

This is worked for my case, not sure this workaround is useful foк anyone other that me.

**Comment by Adiel-Sharabi** [comment]
+1

**Comment by KostasSavvopoulos** [comment]
+1

**Comment by rina-andria** [comment]
+1

**Comment by gogulsekar** [comment]
+1

**Comment by LutsenkoKirill** [comment]
A little workaround is to annotate your OData controller with `    [ApiExplorerSettings(IgnoreApi = false)]`. Your actions will appear in swagger UI but I think you'll than faced with the same problem as @eloekset. 
We really need it!

**Comment by mipil** [comment]
+1

**Comment by jholovacs** [comment]
Adding my +1 on this...

**Comment by faintdeception** [comment]
Ready to migrate some OData api's to .net core and really love Swashbuckle so I guess we'll have to hold off a bit.

**Comment by christianquirante** [comment]
+1

**Comment by christianquirante** [comment]
.net core supports odata now... I really hope swashbuckle.odata can support .net core... I really need swagger for my odata...

**Comment by JohnGalt1717** [comment]
https://github.com/domaindrivendev/Swashbuckle/issues/427

But I find it unfathomable that Microsoft released odata for .net core without fixing the bug with swagger first.  The workaround above still works however.

**Comment by JohnGalt1717** [comment]
For anyone that is looking for a mostly complete oDataQueryParameter filter here it is. It requires that you're using ActionResult<IQueryable>

`
	public class AddOdataQueryParams : IOperationFilter
	{
		public void Apply(Operation operation, OperationFilterContext context)
		{
			if (!context.MethodInfo.GetCustomAttributes(true).OfType<EnableQueryAttribute>().Any())
				return;

			if (operation.Parameters == null)
				operation.Parameters = new List<IParameter>();

			operation.Parameters.Add(new NonBodyParameter
			{
				Name = "$select",
				In = "query",
				Type = "string",
				Description = "Selects the specific fields to return",
				Required = false
			});

			operation.Parameters.Add(new NonBodyParameter
			{
				Name = "$expand",
				In = "query",
				Type = "string",
				Description = "Expands the given properties",
				Required = false
			});


			if (!typeof(IConvertToActionResult).IsAssignableFrom(context.MethodInfo.ReturnType) || 
					!context.MethodInfo.ReturnType.GenericTypeArguments.Any(t => typeof(IQueryable).IsAssignableFrom(t)))
				return;


			operation.Parameters.Add(new NonBodyParameter
			{
				Name = "$skip",
				In = "query",
				Type = "number",
				Format="int32",
				Description = "Skips the first n results",
				Required = false
			});

			operation.Parameters.Add(new NonBodyParameter
			{
				Name = "$top",
				In = "query",
				Type = "number",
				Format = "int32",
				Description = "Returns the first n results",
				Required = false
			});

			operation.Parameters.Add(new NonBodyParameter
			{
				Name = "$filter",
				In = "query",
				Type = "string",
				Description = "Filters the results using oData Notation",
				Required = false
			});
			operation.Parameters.Add(new NonBodyParameter
			{
				Name = "$search",
				In = "query",
				Type = "string",
				Description = "Searches the results using oData Notation",
				Required = false
			});
			operation.Parameters.Add(new NonBodyParameter
			{
				Name = "$orderby",
				In = "query",
				Type = "string",
				Description = "Orders the results by the fields listed",
				Required = false
			});
			operation.Parameters.Add(new NonBodyParameter
			{
				Name = "$count",
				In = "query",
				Type = "boolean",
				Description = "Returns the Count in the results. Useful for pagination",
				Required = false
			});
		}
	}
`

**Comment by aakash1906** [comment]
Combination of
[ApiExplorerSettings(IgnoreApi = false)] on the controller inheriting from ODataController

and

            services.AddMvc(options =>
            {
                foreach (var outputFormatter in options.OutputFormatters.OfType<ODataOutputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
                {
                    outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                }
                foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>().Where(_ => _.SupportedMediaTypes.Count == 0))
                {
                    inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
                }
            }

seems to work. it lists down the ODATA methods too , without the formatter error

**Comment by iqmeta** [comment]
+1

**Comment by GerbenRampaart** [comment]
+1

**Comment by PeterHamiltonTO** [comment]
+1
We NEED this desperately....

**Comment by karolus888** [comment]
+1

**Comment by eddinsw** [comment]
+1

**Comment by ICodeGorilla** [comment]
I found [this](https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-core-with-odata).  Still in beta but does everything I think we need and it is on the Microsoft repo.  Only 100 downloads so I guess that most folks don't know about it

**Comment by ICodeGorilla** [comment]
<p><strong>ASP.NET Core with OData API Explorer</strong> (
<a href="https://www.nuget.org/packages/Microsoft.AspNetCore.OData.Versioning.ApiExplorer" rel="nofollow">nuget</a> |
<a href="/Microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-core-with-odata">quick start</a> |
<a href="/Microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample">samples</a> )
<br>Adds additional API explorer support to your ASP.NET Core applications using OData v4.0</p>

**Comment by reinoboonstra** [comment]
+1

**Comment by vitaliipanchenko** [comment]
+1

**Comment by souchprod** [comment]
+10

**Comment by tchelidze** [comment]
Any updates ?

**Comment by jayoungers** [comment]
For my situation I'm not using OData in the traditional way using ODataController, I'm just using `Microsoft.AspNet.OData.Query.ODataQueryOptions<>` to convert the query parameters into an `IQueryable` for use in my business logic.

Since I'm not using the standard output, adding this in the start up fixes swashbuckle crashing:
```C#
services.AddMvc(options =>
            {
 options.OutputFormatters.RemoveType(typeof(Microsoft.AspNet.OData.Formatter.ODataOutputFormatter));
            })
```

I'm still trying to figure out how to prevent swashbuckle from generating parameters for `ODataQueryOptions<>`: as of now it generates 1000+.  Is there a hook to prevent types from being included in the schema?  I tried using `MapType` during the `AddSwaggerGen` stage but it didn't seem to impact anything

**Comment by wally666** [comment]
Bump

**Comment by julealgon** [comment]
Jumping on the "bump bandwagon". This would be essential for us as well.

**Comment by dacendale** [comment]
+1
This would be huge for us.

**Comment by jbuschke** [comment]
+1, big blocker for us at the moment

**Comment by lelong37** [comment]
+10, Swagger and OData Core working :)

**Comment by andre-engelbrecht** [comment]
@rbeauchamp Would you please provide some feedback on the situation. Are there any plans to support .Net Core, or should we all abandon Swashbuckle and start looking for other solutions? Just a simple indication would be a good start!
Please?

**Comment by AniaDomachowska** [comment]
Hi, is there a chance for the Swagger and Odata Core working?

**Comment by andre-engelbrecht** [comment]
Hi @AniaDomachowska 

The best solution I've found to date is to implement your own DocumentFilter, please refer to this post for more info: https://stackoverflow.com/a/53738397/4261155

**Comment by albertwoo** [comment]
I see "Swashbuckle.OData.Core -Version 1.0.0" released 3 months ago. But how can I use it?

**Comment by breenp** [comment]
+1

**Comment by NBroomfield** [comment]
This might help some people?

https://github.com/Microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample

**Comment by umarlateef** [comment]
no updates?

**Comment by andyward** [comment]
If you're looking to use this library with OData on .net core I can't see it happening without really major fork. I wrote some notes on why that's the case here: https://github.com/rbeauchamp/Swashbuckle.OData/issues/191#issuecomment-462957469

**Comment by NBroomfield** [comment]
Does NSwag work?

**Comment by umarlateef** [comment]
I created this document filter which creates almost everything
https://github.com/umarlateef/netcore_odata_swashbuckle

**Comment by TiagoCastilhos** [comment]
+1

**Comment by sandeep-chinthoju** [comment]
Had an issue using OData with swagger. (swagger UI breaks)

Fix: 
add below code to add supported media types for OData in the end of ConfigureServices method as mentioned by people above.
Make sure you keep this code in the end of the method when you use authentication (I almost spent an hour to make this work because of the order on where it is been kept).

![image](https://user-images.githubusercontent.com/21376275/62974508-fe193e00-bddd-11e9-8c16-3528250c5065.png)

**Comment by bradygaster** [comment]
Question to @rbeauchamp and @domaindrivendev if he has involvement here. I'd like to see what sort of priority we could put on this issue. We'd like to know if this is on the roadmap, could be prioritized, needs assistance, etc. Any chance either would have some time to sync up in the next few days to think about what's possible here?

**Comment by bradygaster** [comment]
one more ping to @domaindrivendev and @rbeauchamp on this. is this something either of you have time to invest in?

**Comment by Lonli-Lokli** [comment]
On behalf of them, it will not be implemented, see https://github.com/rbeauchamp/Swashbuckle.OData/issues/135

I am confused that nobody mentioned another project which gives you all you need https://github.com/microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample

**Comment by domaindrivendev** [comment]
@bradygaster all of my OSS cycles are currently devoted to maturing the core Swashbuckle.AspNetCore functionality. I'm not overly familiar with OData in general so this isn't something  could add to my workload right now.

With that said, if @rbeauchamp were willing to take it on, I'll do my very best to respond promptly to any SB related questions/queries.

**Comment by domaindrivendev** [comment]
@bradygaster have you looked at the project referenced above by @Lonli-Lokli? It does look like it might have what's needed to support Swashbuckle on top of OData.

**Comment by bradygaster** [comment]
Appreciate that advice, @Lonli-Lokli and @domaindrivendev. I'll suggest the customer who pinged me about this take a look. @domaindrivendev - would like to sync up on some other ideas and priorities if you'd have some time to spare. 

thanks to all for the tips.

**Comment by Jamaxack** [comment]
I’m facing the issue: {“StatusCode”:500,”Message”:”System.InvalidOperationException: No media types found in ‘Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes’. Add at least one media type to the list of supported media types.”}

Using: 
.Net core 3.1
Microsoft.AspNetCore.OData 7.4.0-beta

**Comment by Lonli-Lokli** [comment]
@Jamaxack see https://github.com/OData/WebApi/issues/1177#issuecomment-358659774

**Comment by joshcomley** [comment]
@Lonli-Lokli I am having the same issue. I have the `SwaggerODataSample` working perfectly, but in my app I get this media types error - and employing the tactics in your link did not help, unfortunately.

**Comment by joshcomley** [comment]
@Lonli-Lokli @Jamaxack after further investigation, this will work, but you must make sure that `services.AddOData()` comes *before* `services.AddMvcCore(...)`

**Comment by joshcomley** [comment]
Also, the order should be like this if you are using versioning:

	var odata = services.AddOData();
	services.AddMvcCore(...);
	services.AddApiVersioning(...);
	odata.EnableApiVersioning();

**Comment by Lonli-Lokli** [comment]
Just FYI, for the OData Batch order should be as follow
https://github.com/microsoft/aspnet-api-versioning/wiki/OData-Batching

**Comment by andrey-rodin** [comment]
I do not use “pure” OData in my project, just subset of capabilities, namely $top, $skip, $orderby and $filter. Actions that return collections have parameter of type ODataQueryOptions<T>.

At first, my problem was that these parameters were marked with [FromQuery] attribute. Removing this attribute or replacing it by [FromODataUri] plus suggested [workaround](https://github.com/OData/WebApi/issues/1177#issuecomment-358659774) with adjusting OData formatters allows Swashbuckle to work without errors.

Bu Swagger doesn’t understand ODataQueryOptions parameter, so I made decision to introduce four native parameters instead:
```
[FromQuery(Name = "$top")] int top
[FromQuery(Name = "$skip")] int skip
[FromQuery(Name = "$orderby")] string orderby
[FromQuery(Name = "$filter")] string filter
```
Now I create ODataQueryOptions myself with the help of the following class:
```
public static class ODataBuilder
{
    public static ODataQueryOptions<T> BuildOptions<T>(HttpRequest request)
    {
        var modelBuilder = new ODataConventionModelBuilder();
        modelBuilder.AddEntityType(typeof(T));
        var edmModel = modelBuilder.GetEdmModel();
        var oDataQueryContext = new ODataQueryContext(edmModel, typeof(T), new ODataPath());

        return new ODataQueryOptions<T>(oDataQueryContext, request);
    }
}
```
With this approach, Swagger correctly displays OData parameters and allows the user to set them in UI. Maybe my experience can help someone.

**Comment by jayoungers** [comment]
@andrey-rodin - just a heads up, another way to solve the swagger issue is to create your own `IApiDescriptionProvider` that does something like this:

```c#
        constructor(IModelMetadataProvider provider) => this.provider = provider;

        public void OnProvidersExecuting(ApiDescriptionProviderContext context)
        {
            foreach (var result in context.Results)
            {
                ...
                HandleODataReponse(result);
            }
        }

        private void HandleODataReponse(ApiDescription result)
        {
            var odataParam = result.ParameterDescriptions.FirstOrDefault(p => p.ParameterDescriptor.ParameterType.IsGenericType && p.ParameterDescriptor.ParameterType.GetGenericTypeDefinition() == typeof(ODataQueryOptions<>));
            if (odataParam != null)
            {
                result.ParameterDescriptions.Remove(odataParam);
                result.ParameterDescriptions.Add(new ApiParameterDescription
                {
                    Name = "$filter",
                    ModelMetadata = provider.GetMetadataForType(typeof(string)),
                    Source = BindingSource.Query
                });
                result.ParameterDescriptions.Add(new ApiParameterDescription
                {
                    Name = "$orderby",
                    ModelMetadata = provider.GetMetadataForType(typeof(string)),
                    Source = BindingSource.Query
                });
                result.ParameterDescriptions.Add(new ApiParameterDescription
                {
                    Name = "$top",
                    ModelMetadata = provider.GetMetadataForType(typeof(int)),
                    Source = BindingSource.Query
                });
                result.ParameterDescriptions.Add(new ApiParameterDescription
                {
                    Name = "$skip",
                    ModelMetadata = provider.GetMetadataForType(typeof(int)),
                    Source = BindingSource.Query
                });
                result.ParameterDescriptions.Add(new ApiParameterDescription
                {
                    Name = "$count",
                    ModelMetadata = provider.GetMetadataForType(typeof(bool)),
                    Source = BindingSource.Query
                });
            }
        }
```

**Comment by pravinchandankhede** [comment]
> Had an issue using OData with swagger. (swagger UI breaks)
> 
> Fix:
> add below code to add supported media types for OData in the end of ConfigureServices method as mentioned by people above.
> Make sure you keep this code in the end of the method when you use authentication (I almost spent an hour to make this work because of the order on where it is been kept).
> 
> ![image](https://user-images.githubusercontent.com/21376275/62974508-fe193e00-bddd-11e9-8c16-3528250c5065.png)

Putting the code in last worked for me. earlier I had it somewhere in beginning didn't worked. Thanks

**Comment by alexzheludov** [comment]
> @andrey-rodin - just a heads up, another way to solve the swagger issue is to create your own `IApiDescriptionProvider` that does something like this:
> 
> ```cs
>         constructor(IModelMetadataProvider provider) => this.provider = provider;
> 
>         public void OnProvidersExecuting(ApiDescriptionProviderContext context)
>         {
>             foreach (var result in context.Results)
>             {
>                 ...
>                 HandleODataReponse(result);
>             }
>         }
> 
>         private void HandleODataReponse(ApiDescription result)
>         {
>             var odataParam = result.ParameterDescriptions.FirstOrDefault(p => p.ParameterDescriptor.ParameterType.IsGenericType && p.ParameterDescriptor.ParameterType.GetGenericTypeDefinition() == typeof(ODataQueryOptions<>));
>             if (odataParam != null)
>             {
>                 result.ParameterDescriptions.Remove(odataParam);
>                 result.ParameterDescriptions.Add(new ApiParameterDescription
>                 {
>                     Name = "$filter",
>                     ModelMetadata = provider.GetMetadataForType(typeof(string)),
>                     Source = BindingSource.Query
>                 });
>                 result.ParameterDescriptions.Add(new ApiParameterDescription
>                 {
>                     Name = "$orderby",
>                     ModelMetadata = provider.GetMetadataForType(typeof(string)),
>                     Source = BindingSource.Query
>                 });
>                 result.ParameterDescriptions.Add(new ApiParameterDescription
>                 {
>                     Name = "$top",
>                     ModelMetadata = provider.GetMetadataForType(typeof(int)),
>                     Source = BindingSource.Query
>                 });
>                 result.ParameterDescriptions.Add(new ApiParameterDescription
>                 {
>                     Name = "$skip",
>                     ModelMetadata = provider.GetMetadataForType(typeof(int)),
>                     Source = BindingSource.Query
>                 });
>                 result.ParameterDescriptions.Add(new ApiParameterDescription
>                 {
>                     Name = "$count",
>                     ModelMetadata = provider.GetMetadataForType(typeof(bool)),
>                     Source = BindingSource.Query
>                 });
>             }
>         }
> ```

This worked for me! Thank you for sharing!

**Comment by collinbarrett** [comment]
I'm fairly new to OData and am having a hard time tracing down current Swagger support. I have a skeleton API rebuild working with OData, Swashbuckle, and API Versioning. However, by default, there doesn't seem to be a way to use the OData query options in the Swagger UI "Try it out" playground.

Is that what this issue is about? Or was this issue just about getting `ODataController` actions available in `swagger.json` at all (which as of today seems to be supported).

I was able to successfully add  rudimentary support for this using @jayoungers [example](https://github.com/rbeauchamp/Swashbuckle.OData/issues/154#issuecomment-600650807) in my api [here](https://github.com/collinbarrett/FilterLists/blob/dad75c53b37bb91e83ea45668372fd36eae96ef5/svr/src/FilterLists.Api/Infrastructure/OData/ODataQueryOptionApiDescriptionProvider.cs). But, I just wanted to confirm that there is no maintained option for using OData query options in the Swagger UI? If not, that's cool. I just want to make sure before I go down the path of doing this all custom using reflection, etc.
