### ISSUE TITLE
 Swashbuckle.OData integration issues with OData V3 Controllers

### ISSUE THREAD

**Issue by ss27051980** [rbeauchamp/Swashbuckle.OData#159]
Swashbuckle.OData seems to have integration issues with OData V3 Controllers.I can see the end points on swagger UI, however UI cant fetch the data due to incorrect route prefix 'api' taken by the framework. The end points are working perfectly when testing using postman.The other approach tried is to use explicit RoutePrefix on ODataController, this helped the Swagger UI show the RoutePrefix 'odata', however this causes the api to break completely and now we are not able to query or fetch data from Postman as well.This is really frustrating, any guidance on this would be really helpful.

I have uploaded the sample solution in the following git Repo .. ##https://github.com/ss27051980/Swagger-OData.git##

**Comment by Joseris** [comment]
We're also stuck with OData v3 and based on https://github.com/rbeauchamp/Swashbuckle.OData/issues/90 there are no support for V3.
