### ISSUE TITLE
Added configuration to Web API and OData project throws a NullReferenceException

### ISSUE THREAD

**Issue by aibars** [rbeauchamp/Swashbuckle.OData#160]
Hi, 

I have the following question. I have a _normal_ versioned Web API application which I have added recently some OData controllers to it. Such controllers work fine. The solution also has Swashbuckle configured.
I now want to be able to list the OData controllers and endpoints as well. The problem is that after adding the configuration on the example here, I'm getting a `NullReferenceException` on the following line from `HttpConfigurationExceptions`  in the `GetODataRootContainer` method:
```
return (IServiceProvider)GetODataRootContainerMethod.Invoke(null, new object[] {configuration, oDataRoute.PathRouteConstraint.RouteName});
```

It seems that the oDataRoute.PathRouteConstraint is null.
Could you tell me what am I doing wrong? The app does not use OWIN. 

Here's my Swagger config:

```
GlobalConfiguration.Configuration
                .EnableSwagger(c =>
                    {
                        c.MultipleApiVersions(
                            (apiDesc, targetApiVersion) => ResolveVersionSupportByRouteConstraint(apiDesc, targetApiVersion),
                            (vc) =>
                            {
                                vc.Version("v1", "API v1");
                            });

                        c.CustomProvider(defaultProvider => new ODataSwaggerProvider(defaultProvider, c, GlobalConfiguration.Configuration).Configure(odataConfig =>
                        {
                            odataConfig.IncludeNavigationProperties();
                        }));
                    })
```

Thank you. 
Agustín

**Comment by AbhishekKamble** [comment]
Hi,

Did you find any solution for path root constraint null exception problem.

Regards,
Abhishek.

**Comment by SupportNegometal** [comment]
Hi,

Bump, we are facing the same issue :(
