### ISSUE TITLE
ODataMetadata Endpoint

### ISSUE THREAD

**Issue by carand315** [rbeauchamp/Swashbuckle.OData#163]
Hi, I would like to know what means ODataEnpoint appears in Swagger UI. Can it hide? I'm using a versioned API's. Thanks.

![image](https://user-images.githubusercontent.com/12404236/30970489-deaf58e8-a42a-11e7-8abd-017bc6b78c57.png)

**Comment by matzheng** [comment]
I got the same issue.
ODataMetadata won't show when single version applied.
