### ISSUE TITLE
ODataQueryOptions causes extra definitions to be created

### ISSUE THREAD

**Issue by andyward** [rbeauchamp/Swashbuckle.OData#168]
When an OData controller action has an `ODataQueryOptions` parameter this seems to cause the ODataQueryOptions type to be picked up as a normal input parameter, which the  gets defined in the the Swagger JSON definitions/params. This also results in the Swagger UI expecting the OData options to be supplied as a parameter.

E.g. Amending the CustomersController in the Samples projects as follows:

``` csharp
[EnableQuery(PageSize = 5)]
public async Task<IHttpActionResult> Get(ODataQueryOptions<Customer> options)
{
    var customers = await _db.Customers.ToListAsync();
    return Ok(customers);
}
```
... results in this Swagger output
![image](https://user-images.githubusercontent.com/923699/32338934-204c3cec-bfee-11e7-8579-fa1c92c44de5.png)

In the Swagger UI this is manifested as an extra parameter on the Action. E.g. 
![image](https://user-images.githubusercontent.com/923699/32339214-012bfcca-bfef-11e7-88e7-b456910913cf.png)

I've got a simple fix for this, with a covering test. Happy to put in a PR if that helps. It's a one-line fix to **ODataActionDescriptorMapperBase.CreateParameterDescriptions** to check  `parameterBinding.Descriptor.IsODataLibraryType()` before adding.

**Comment by rbeauchamp** [comment]
Fixed in https://www.nuget.org/packages/Swashbuckle.OData/3.4.1
