### ISSUE TITLE
Error: Segments with mutiple keys

### ISSUE THREAD

**Issue by joshbooker** [rbeauchamp/Swashbuckle.OData#18]
500 : {"Message":"An error has occurred.","ExceptionMessage":"Segments with multiple key values must specify them in 'name=value' form.","ExceptionType":"Microsoft.OData.Core.ODataException","StackTrace":" at Microsoft.OData.Core.UriParser.Parsers.SegmentKeyHandler.CreateKeySegment(ODataPathSegment segment, KeySegment previousKeySegment, SegmentArgumentParser key, ODataUriResolver resolver)\r\n at Microsoft.OData.Core.UriParser.Parsers.SegmentKeyHandler.TryCreateKeySegmentFromParentheses(ODataPathSegment previous, KeySegment previousKeySegment, String parenthesisExpression, ODataPathSegment& keySegment, Boolean enableUriTemplateParsing, ODataUriResolver resolver)\r\n at Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.TryBindKeyFromParentheses(String parenthesesSection)\r\n at Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.TryCreateSegmentForNavigationSource(String identifier, String parenthesisExpression)\r\n at Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.CreateFirstSegment(String segmentText)\r\n at Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.ParsePath(ICollection`1 segments)\r\n at Microsoft.OData.Core.UriParser.Parsers.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)\r\n at Microsoft.OData.Core.UriParser.ODataUriParser.ParsePathImplementation()\r\n at Microsoft.OData.Core.UriParser.ODataUriParser.Initialize()\r\n at Microsoft.OData.Core.UriParser.ODataUriParser.ParsePath()\r\n at System.Web.OData.Routing.DefaultODataPathHandler.Parse(IEdmModel model, String serviceRoot, String odataPath, ODataUriResolverSetttings resolverSettings, Boolean enableUriTemplateParsing)\r\n at System.Web.OData.Routing.DefaultODataPathHandler.Parse(IEdmModel model, String serviceRoot, String odataPath)\r\n at Swashbuckle.OData.ODataApiExplorer.GenerateSampleODataPath(ODataRoute oDataRoute, String sampleODataAbsoluteUri)\r\n at Swashbuckle.OData.ODataApiExplorer.GetApiDescription(HttpMethod httpMethod, ODataRoute oDataRoute, String potentialPathTemplate, Operation potentialOperation)\r\n at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions(ODataRoute oDataRoute, String potentialPathTemplate, PathItem potentialOperations)\r\n at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions(ODataRoute oDataRoute)\r\n at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions()\r\n at System.Lazy`1.CreateValue()\r\n at System.Lazy`1.LazyInitValue()\r\n at System.Lazy`1.get_Value()\r\n at Swashbuckle.OData.ODataApiExplorer.get_ApiDescriptions()\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken )\r\n at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"} http://localhost:57336/swagger/docs/v1

**Comment by joshbooker** [comment]
Might be able to repeat with something like this:

    namespace NorthwindAPI.Models
    {
        using System;
        using System.Collections.Generic;
        using System.ComponentModel.DataAnnotations;
        using System.ComponentModel.DataAnnotations.Schema;
        using System.Data.Entity.Spatial;

        [Table("Order Details")]
        public partial class Order_Detail
        {
            [Key]
            [Column(Order = 0)]
            [DatabaseGenerated(DatabaseGeneratedOption.None)]
            public int OrderID { get; set; }

            [Key]
            [Column(Order = 1)]
            [DatabaseGenerated(DatabaseGeneratedOption.None)]
            public int ProductID { get; set; }

            [Column(TypeName = "money")]
            public decimal UnitPrice { get; set; }

            public short Quantity { get; set; }

            public float Discount { get; set; }

            public virtual Order Order { get; set; }

            public virtual Product Product { get; set; }
        }
    }

**Comment by joshbooker** [comment]
Repro repo here:
https://github.com/joshbooker/NorthwindAPI

**Comment by rbeauchamp-lendingtree** [comment]
Thanks for testing this out and providing the repo! NorwindAPI tests should give some good code and use case coverage.

**Comment by rbeauchamp-lendingtree** [comment]
Hey Josh, the fix is available in [v2.5.2](https://www.nuget.org/packages/Swashbuckle.OData/2.5.2)

**Comment by joshbooker** [comment]
Nice!  Thanks Richard.  Works great!  Northwind demo here:
http://bit.ly/1QNR6Au

**Comment by rbeauchamp** [comment]
Nice! Thanks for the demo!
