### ISSUE TITLE
camelCasing for REST API

### ISSUE THREAD

**Issue by chauey** [rbeauchamp/Swashbuckle.OData#19]
Hi there @rbeauchamp, curious how to get the camelCasing to work? I think your live example also does not have. Do you not need or want that? A few weeks ago I tried using techniques found online for WEB API 2, but to no avail. thx

**Comment by rbeauchamp-lendingtree** [comment]
Hey @chauey, please explain or provide a Gist on what you are looking for in terms of the Swagger-UI? What piece(s) of the UI do you want camel cased?

**Comment by rbeauchamp-lendingtree** [comment]
Hey @chauey, I'll re-open this after you provide some more detail. Thanks!

**Comment by chauey** [comment]
@rbeauchamp Hi there, I meant the JSON data. Customer.Name, how to change it to customer.name so that only the .NET server code see's ProperCasing for entities and their properties, and everything from the REST API and front-end see camelCasing?

**Comment by rbeauchamp-lendingtree** [comment]
@chauey Thanks for the info. I'll research this.

**Comment by chauey** [comment]
Perhaps related to code like this somewhere:

 

config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();

**Comment by rbeauchamp-lendingtree** [comment]
Hey @chauey, set these two things:

In your application startup:
```
httpConfig.Formatters.JsonFormatter.SerializerSettings.ContractResolver 
= new CamelCasePropertyNamesContractResolver();
```
Where you build your EDM model:
```
var builder = new ODataConventionModelBuilder();
builder.EnableLowerCamelCase(); //<----
return builder.GetEdmModel();
```

**Comment by chauey** [comment]
Thanks, I did not have the builder.EnabledLowerCamelCase() in the right place; had it set too late, moved it up... cheers!
