### ISSUE TITLE
Need Help OData V4 REST Web API Documentation 

### ISSUE THREAD

**Issue by kuldip1490** [rbeauchamp/Swashbuckle.OData#193]
I m using  Microsoft.AspNet.OData v7.1.0 , I want to make documentation using swagger .
Any one can guide me to make documentation of OData V4  Web API

**Comment by andyward** [comment]
Take a look at my notes on https://github.com/rbeauchamp/Swashbuckle.OData/issues/191#issuecomment-462957469

I have a fork that works on OData 7.x under netframework

**Comment by kuldip1490** [comment]
Installed Swashbuckle.OData.Core  and i got below error
![1](https://user-images.githubusercontent.com/22524273/59766738-7d96ff00-92be-11e9-94f8-b68e9593d4db.png)

**Comment by andyward** [comment]
Are you calling `HttpConfiguration.EnsureInitialised()` ? 

Make sure it's called just after you set up the the OData routes

**Comment by kuldip1490** [comment]
@andyward  Thank you for your guidance . I just got my outputs . Thank you
