### ISSUE TITLE
Nice Work! Would global routes help eliminate path magic string?

### ISSUE THREAD

**Issue by joshbooker** [rbeauchamp/Swashbuckle.OData#2]
First this is great work.  I hope WebAPI OData team will work their implementation into swashbuckle like this - out of the box.  

https://github.com/OData/WebApi/issues/302
https://github.com/OData/WebApi/pull/520
https://github.com/OData/WebApi/issues/552

I wonder if you can get global ODataRoutes to eliminate the '/odata' magic string:
something like:

var odataRoutes = GlobalConfiguration.Configuration.Routes.Where(a=>a.GetType() == typeof(ODataRoute)).ToList();
if (!odataRoutes.Any()) return;
var route = odataRoutes.FirstOrDefault() as ODataRoute;
var path = "/" + route.RoutePrefix;
c.CustomProvider(defaultProvider => new ODataSwaggerProvider(path, edmModel));  

Or better yet, maybe do it in ODataSwaggerProvider so you don't need to pass edm through SwaggerConfig.

PS - side question:  have you tested to see whether swashbuckle filters work to post-modify swagger output?  CUrious if IOperationFilter works for custom ISwaggerProvider.

Keep up the great work!

**Comment by rbeauchamp-lendingtree** [comment]
@joshbooker Thanks Josh! I'll try your idea to see if we can get rid of the hardcoded/magic string.

PS, No, I haven't tested yet whether filters are applied after setting the custom ISwaggerProvider.

**Comment by rbeauchamp-lendingtree** [comment]
@joshbooker Now determining the route prefix in the ODataSwaggerProvider. This significantly simplified the configuration steps. Thanks for your suggestion!

**Comment by rbeauchamp-lendingtree** [comment]
Fix is available in this pre-release [NuGet package](https://www.nuget.org/packages/Swashbuckle.OData/2.0.0-alpha-1)

**Comment by joshbooker** [comment]
That's perfect!  One line in swagger.config and done. Great work.  You really need to submit this as pull request to webapi odata. As you know they've been very responsive to issue 302 in recent days. If submitted now, your provider code might just make v5.8

**Comment by joshbooker** [comment]
Must try this with RESTier tomorrow. Thanks again for sharing.

**Comment by joshbooker** [comment]
Richard, I got an email from OData PM Mark Stafford, says they'll look at this next week  and update github after holiday.  

PS You may want to change readme to install nuget prerelease:
Install-Package Swashbuckle.OData -pre

**Comment by rbeauchamp-lendingtree** [comment]
@joshbooker Hey Josh, Ok, thanks for the OData PM update. Sure, I'll change the readme. Thanks!

**Comment by joshbooker** [comment]
Thanks again. PS works great with https://github.com/OData/RESTier too. Happy happy

**Comment by rbeauchamp-lendingtree** [comment]
Cool!

**Comment by joshbooker** [comment]
@rbeauchamp FYI discussion about adding this to System.Web.OData is ongogin here:
OData/WebApi#520

**Comment by rbeauchamp-lendingtree** [comment]
@joshbooker OK. Thanks for the update.

FYI, Item 3) from your comment is not implemented at this time. See my comment in https://github.com/rbeauchamp/Swashbuckle.OData/issues/5.

**Comment by joshbooker** [comment]
@rbeauchamp-lendingtree I was going to test IOperationFilter in SwaggerConfig.cs and find if it affects swagger output.  The swashbuckle docs don't clarify this.  Are you says you did so and it does not post- modify?
