### ISSUE TITLE
Custom Routing with OData

### ISSUE THREAD

**Issue by darewreck54** [rbeauchamp/Swashbuckle.OData#21]
Hi,

In my project, I overrided the EntitySetRoutingConvention class that override the selectAction and selectController method for custom routing.  The swagger doesn't seem to pick up the correct routes.  

Not sure if this is really an issue vs. a question.

Example:

Actual route:  /Products(1)/Suppliers       Controller in this case: Suppliers
Swagger display route: /Products            Controller in this case: Products

since it only recognizes the default controllers vs. the custom routing where it would return supplies as the controller)

Is there any specific Annotation that can resolve this issue?  
Thanks!

**Comment by rbeauchamp** [comment]
Hey would you mind throwing together a gist so I can reproduce the issue? Or point me to your code or unit test? Not sure I fully understand your scenario.

**Comment by darewreck54** [comment]
Sure thing, I'll try to modify the provided example and send you It. 

Derek

**Comment by darewreck54** [comment]
DL the project: https://onedrive.live.com/redir?resid=30915BBAD31877D9!423&authkey=!AOY-QGFbUmbyJu4&ithint=file%2czip

With a restful client, trigger the following request:
POSTURL: http://localhost:4073/odata/Customers(1)/OrdersPayload: { "OrderName": "323"}
This request is to create a Order under Customer 1.
Put a break point in OrdersController.cs : 
 public  Task<IHttpActionResult> Post([FromODataUri] int CustomerID,  Order patch)        {            throw new NotImplementedException();        }
Notice that in this call, the custom routing will trigger OrdersController instead of the CustomersController.   It will trigger a Post Action.  So the flow works as expected.
However, when you look at http://localhost:4073/swagger/ui/index#/ and look at the Customer or Order controller the path does not exist.
So I would expect to see Under OrderController or CustomerController:
/odata/Customer({key})/Orders
Questions:Are there attribute that I can add to the function that swagger would recognize and display the path in the swagger UII imagine that the swashbuckle.odata code would look at all the signature function and recognize that there is a Post function that takes in a customerID in the URL and is a post action.  But it also accounts for the custom routing.  Is that possible?
Let me know if that make sense?Thanks,
Derek

**Comment by rbeauchamp** [comment]
Hey Derek, thank you for posting the example code. I've downloaded it and am able to reproduce the issue. I'll investigate and get back to you.

**Comment by rbeauchamp** [comment]
Hey @darewreck54, support for custom routes is now available in release [v2.6.0](https://www.nuget.org/packages/Swashbuckle.OData/2.6.0). Here's the new[ documentation](https://github.com/rbeauchamp/Swashbuckle.OData#custom-routes). Give it a try and let me know how it works for you.

**Comment by darewreck54** [comment]
Thank.  I took a look and tried out the fix.  It looks like it works.  Great work!
I haven't had a chance to really take a look at the inner workings of the swashbuckle.OData code base, so please bear with me.  Here are some suggestions (not sure how difficult or complex it would be):
The extra steps that you require the user to define the custom route seems a bit much.  The reason being is that the user would have to do this for every single route at this point because of the injected custom route class.  From my understanding the key appeal of swagger/swashbuckle is that it automatically scans the code with little additional work on the user side to display the endpoints.  If that is true, here are some suggestions:If you choose this method, is it possible to trigger off special OData attribute similar to Route(" ") on top of every function in the controller for custom routes.  This will make the code more readable/maintainable.  If the function has say a special attribute "[ODataCustomRoute("")] then trigger off that.  By doing this, you wouldn't have to specify the Controller or even the parameters in the config file since you have all that info from being in the Controller class and the attribute would be connected to the function signature where you can attract the params.  If that is too complicated, you can just have the user associate the attributes at the controller level.  Another possible way to resolve the issue, is it possible to take advantage of the return functions of the custom route class.  The custom route class overrides two functions.  SelectAction & SelectController.   When the application starts up & swagger OData starts scanning the code for endpoints, is it possible to use the custom route class to retrieve the Controller (This eliminates the need to specify the controller) and also the action (eliminates the need to specify the action) and then be able to determine the paramaters via function definition in the code.
Please let me know if the suggestions make sense,Thanks,
Derek
Date: Sat, 19 Dec 2015 09:03:52 -0800

**Comment by rbeauchamp** [comment]
Glad it works! I'll investigate your suggestions. Probably after I get through the other recent issues. Thanks for your feedback; I see how defining a custom route for every action could be cumbersome.

**Comment by darewreck54** [comment]
Can you open this up for possible enhancement in terms of using the definition instead of having to directly do AddCustomeRoute() Or should I create another issue just for enhancement?

**Comment by rbeauchamp** [comment]
A new issue would be good. One that describes exactly how you think it should work.

**Comment by rbeauchamp** [comment]
And when I say 'how you think it should work' I mean from a user perspective. Thanks.
