### ISSUE TITLE
Support for OData Containment

### ISSUE THREAD

**Issue by aaronwjha** [rbeauchamp/Swashbuckle.OData#24]
We've implemented some new routes using Containment and they are not documented correctly. Here is a sample project that will help reproduce the problem:

https://aspnet.codeplex.com/SourceControl/latest#Samples/WebApi/OData/v4/ODataContainmentSample/

Thanks for looking into this!

**Comment by rbeauchamp** [comment]
I'll look into it. Thanks for referencing the sample project; that helps.

**Comment by rbeauchamp-lendingtree** [comment]
Hi @aaronwjha, support is now available in [v2.7.0](https://www.nuget.org/packages/Swashbuckle.OData/2.7.0). Please give a try and let me know if you have any issues.

**Comment by aaronwjha** [comment]
Thanks! Contained routes are now documented, but queryable calls do not include support for query params in the Swagger UI. Are you able to repro this?

**Comment by rbeauchamp-lendingtree** [comment]
Ah yes, good catch. Would you mind creating a new issue for this? Something like: 'Provide query options in swagger UI for queryable ODataController actions" (I.e., controller actions that have the EnableQuery attribute applied.) I think this covers the issue/scenario you are referring to? (Don't think this is related, particularly, to containment.)
