### ISSUE TITLE
Limit graph nesting

### ISSUE THREAD

**Issue by stimpy77** [rbeauchamp/Swashbuckle.OData#25]
Is there a way to limit graph nesting, like telling it to include no deeper than 2 levels of navigation properties?

I'm not sure if this is an Swashbuckle.OData issue or a Swashbuckle issue, but we have a model being returned that, in the way it is used, would normally have null navigation properties at the second or third level, but Swashbuckle.OData is outputting a response object graph that is like 10 levels deep, so the browser locks up for a long time or blows up with out of memory exceptions.

**Comment by rbeauchamp** [comment]
Will research and get back to you.

**Comment by rbeauchamp** [comment]
Hey @stimpy77, graph nesting is now limited to the top-level entity in [v2.8.0](https://www.nuget.org/packages/Swashbuckle.OData/2.8.0). Give it a try and let me know if you find any issues. Thanks!
