### ISSUE TITLE
Router not registering with string based keys

### ISSUE THREAD

**Issue by patrickmichalina** [rbeauchamp/Swashbuckle.OData#31]
By default the route created with swagger for the delete operation looks like this: 

`https://localhost:44300/odata/v1/SafetyEquipment(testthis!)`

but that wont work because the way to use a string based key is to surround the string with quotes in the parenthesis like so:

`https://localhost:44300/odata/v1/SafetyEquipment('testthis!')`

The result is a 404 because that route (the one without quotes) doesn't exist.

from the controller:
```
public virtual async Task<IHttpActionResult> Delete([FromODataUri] string key)
{
    // delete tasks
}
```

**Comment by rbeauchamp-lendingtree** [comment]
Hey @patrickmichalina, thank you for posting this. The work-around for now is to put single quotes around the string parameters in the Swagger UI. I'm working on a fix and will let you know when ready.

**Comment by rbeauchamp-lendingtree** [comment]
@patrickmichalina Fixed in [v2.7.1](https://www.nuget.org/packages/Swashbuckle.OData/2.7.1). Please give it a try and let me know if you find any issues. Thanks!

**Comment by patrickmichalina** [comment]
@rbeauchamp-lendingtree it works! I appreciate the fast turn around... I can't believe I didn't consider just wrapping those values in quotes in the swagger-ui >.<

**Comment by rbeauchamp** [comment]
Nice! :-)
