### ISSUE TITLE
Provide query options in swagger UI for queryable ODataController actions

### ISSUE THREAD

**Issue by aaronwjha** [rbeauchamp/Swashbuckle.OData#37]
May or may not be related to https://github.com/rbeauchamp/Swashbuckle.OData/issues/24

**Comment by rbeauchamp-lendingtree** [comment]
@aaronwjha Thanks!

**Comment by rbeauchamp-lendingtree** [comment]
Hi @aaronwjha, this feature is now available in v2.9.0. Please give a try and let me know if you have any issues. Thanks!
