### ISSUE TITLE
Version 2 nuget installation

### ISSUE THREAD

**Issue by codepb** [rbeauchamp/Swashbuckle.OData#4]
Hi,

I am trying to install the new version of the nuget package to a .Net 4.5 application but I am getting the following error:

Could not install package 'Swashbuckle.OData 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by codepb** [comment]
It seems this only supports .Net 4.6 (or maybe .Net 4.5.2) it certainly didn't work with .Net 4.5.1 or below.

**Comment by rbeauchamp-lendingtree** [comment]
Hi @codepb, yes, Swashbuckle.OData v2.0.0 has a dependency on .Net 4.5.2. See the [NuGet page](https://www.nuget.org/packages/Swashbuckle.OData/) for the full set of dependencies.

**Comment by rbeauchamp-lendingtree** [comment]
Updated the README to be clear that the dependency is on .Net 4.5.2. Thanks.
