### ISSUE TITLE
Split oDataController from ApiController

### ISSUE THREAD

**Issue by lakeba** [rbeauchamp/Swashbuckle.OData#42]
I am trying to keep separate in two different URL the docs for oData controllers and the docs for Api Controllers.

Is it doable?

Thank you

**Comment by rbeauchamp-lendingtree** [comment]
I'm not sure exactly, but maybe via the [versioning capability](https://github.com/domaindrivendev/Swashbuckle#describing-multiple-api-versions) of swashbuckle/swagger? The API 'version' and the OData 'version'...
