### ISSUE TITLE
$ref Odata support?

### ISSUE THREAD

**Issue by darewreck54** [rbeauchamp/Swashbuckle.OData#44]
In the article, it mentions Creating/Deleting a Relationship Between Entities for Odata v4 WebApi2:

Here is the link: http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/entity-relations-in-odata-v4

Does the swashbuckle.Odata support $ref and also does custom setting need to be done to make it show up?

**Comment by rbeauchamp** [comment]
Hey D, 

> Does the swashbuckle.Odata support $ref

nope

> and also does custom setting need to be done...

Haven't tried. If you try it, please let us know the results.

**Comment by darewreck54** [comment]
Is it possible to add this as an enhancement request? I believe swagger json does give the capability to do this.

Thanks
D

**Comment by rbeauchamp** [comment]
If you need this feature, any chance you can implement it? On a go forward basis, to prevent burnout and stay motivated, I'm going to [draw a line in the sand](http://blog.many-monkeys.com/a-line-in-the-sand/) and only personally 
implement features that I personally need. If you do implement it,  please submit it via a pull request and also include a unit test that covers the functionality. (You'll notice that I now track code coverage and am shooting for 100% coverage in the unit tests.)

**Comment by rbeauchamp** [comment]
I think you would implement something like
```
routes.AddRangeIfNotNull(GenerateEntityRelationRoutes(oDataRoute));
```
in [EntityDataModelRouteGenerator](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/Descriptions/EntityDataModelRouteGenerator.cs).

**Comment by darewreck54** [comment]
I'll try to take a look at it.  I need to figure out how swagger handles ref correctly in terms of json.

**Comment by patrickmichalina** [comment]
This is interesting! Might take a look at it.

**Comment by rbeauchamp** [comment]
That would be nice!

**Comment by rbeauchamp** [comment]
Closing this old feature request as it is not important enough for someone to spend the time to implement it.
