### ISSUE TITLE
Only primitive types when use CustomProvider

### ISSUE THREAD

**Issue by lakeba** [rbeauchamp/Swashbuckle.OData#46]
Hi,
the use of the following line is hiding all the no primitive type property in the Swagger JSON. 

c.CustomProvider(defaultProvider => new ODataSwaggerProvider(defaultProvider, c));

example:

.NET

public int Id { get; set; }
public string Name { get; set; }
public bool ReadPermission { get; set; }
public bool WritePermission { get; set; }
**public ICollection<IPDto> IPWhitelist { get; set; }**
public string ApiKey { get; set; }
public string ApiSecret { get; set; }
public bool IsActive { get; set; }

JSON

{
  "Id": 0,
  "Name": "string",
  "ReadPermission": true,
  "WritePermission": true,
  "ApiKey": "string",
  "ApiSecret": "string",
  "IsActive": true
}

**Comment by rbeauchamp** [comment]
If you do a straight OData GET against your entity set, the model returned looks like that JSON, yes? I'm trying to show the data model as it will be returned by default (when you don't use $expand). The full model can be viewed via the metadata link. Does that work?

**Comment by lakeba** [comment]
Rob,
The problem is related to the swagger docs look below:

**before:**

![screen shot 2016-01-05 at 7 58 25 am](https://cloud.githubusercontent.com/assets/1730650/12109379/a5986086-b381-11e5-94c4-217026855e66.png)

**after:**
![screen shot 2016-01-05 at 7 57 57 am](https://cloud.githubusercontent.com/assets/1730650/12109387/bbd41ce6-b381-11e5-8b7b-3f0ff09439ac.png)

**Comment by lakeba** [comment]
Sorry to bother you, any news about this bug? We have the extension installed on our production server and just want to know if the bug is solvable.

**Comment by rbeauchamp** [comment]
It is solvable with a code change. So thats not an ODATA API?

**Comment by lakeba** [comment]
Exactly, the error happens only on NOT ODATA API.

**Comment by rbeauchamp** [comment]
ok. I'll work on excluding web apis from this feature.

**Comment by lakeba** [comment]
What exactly you mean for excluding web apis from this feature?

**Comment by rbeauchamp-lendingtree** [comment]
Well, limiting the object graph is currently a 'feature' based upon [this issue](https://github.com/rbeauchamp/Swashbuckle.OData/issues/25): only the top level properties are displayed in the swagger model, similar to how OData returns data (if you don't $expand the relationships).

So I could go one of two ways:
1. Make this feature configurable such that it can be completely disabled for both OData and WebApi routes.
2. Only apply this feature to OData routes.

Thoughts?

**Comment by lakeba** [comment]
Rich,
I think that the issue mentioned in your post is not a real issue but a missed use of DTO's.

I would suggest to remove this limitation or waste case make it configurable for each controller type oData or WebApi.

**Comment by rbeauchamp-lendingtree** [comment]
OK. Will think about it. One issue I've found with OData is that it doesn't nicely support the use of DTOs like WebApi does; i really wish it did. I think Restier is trying to help with that. For POSTs and GETs plain OData requires the full entity and thus pulls along all of its relationships which can be extensive especially if you have a normalized entity data model.

I couldn't figure out how just limit the swagger graph to 2 levels deep so at this point it's all levels or only 1 level...

**Comment by lakeba** [comment]
Using this solution I can use DTO's in .NET without any problem: 
http://www.briankeating.net/post/WebAPI-OData-DTO

**Comment by rbeauchamp-lendingtree** [comment]
@lakeba Cool! Thanks for the link. This is off topic from this issue, but your same OData controllers support a complete set of HTTP methods, GET, POST, PUT, etc, within the same controller? I typically have different DTOs for POSTS vs PATCH, for example, as some data can be created but not modified. I can do this easily with WebAPI...

**Comment by rbeauchamp-lendingtree** [comment]
OK. Here are my current thoughts: Swashbuckle.OData should, by default, support the idiomatic or "default" usage of OData which at this point is full entities rather than DTOs. DTOs is an atypical usage of OData (although I do like the DTO approach).

So I think it makes sense to

1. Assume full entities and only display top-level properties by default, 
but
2. Provide the capability via configuration to display the full graph. I'll provide this capability soon. 

Thanks.

**Comment by rbeauchamp-lendingtree** [comment]
Hey @lakeba, items 1 and 3 are now implemented in v2.9.3 and should fix your issue. I'll see if anyone asks for item 2 (or provides a pull request!) before implementing.
