### ISSUE TITLE
Enhancement to Custom Routing

### ISSUE THREAD

**Issue by darewreck54** [rbeauchamp/Swashbuckle.OData#49]
I haven't had a chance to really take a look at the inner workings of the swashbuckle.OData code base, so please bear with me.  

Here are some suggestions (not sure how difficult or complex it would be):

Problem: 

The extra steps that you require the user to define the custom route seems a bit much.  The reason being is that the user would have to do this for every single route at this point because of the injected custom route class.  From my understanding the key appeal of swagger/swashbuckle is that it automatically scans the code with little additional work on the user side to display the endpoints. If that is true, here are some suggestions:

Suggestion: 

1) If you choose this method, is it possible to trigger off special OData attribute similar to Route(" ") on top of every function in the controller for custom routes.  This will make the code more readable/maintainable.  If the function has say a special attribute "[ODataCustomRoute("")] then trigger off that.  By doing this, you wouldn't have to specify the Controller or even the parameters in the config file since you have all that info from being in the Controller class and the attribute would be connected to the function signature where you can attract the params.  

2) If that is too complicated, you can just have the user associate the attributes at the controller level.  

3) Another possible way to resolve the issue, is it possible to take advantage of the return functions of the custom route class. 

I'm not really sure how the code scan for routes works, so not sure if this is possible.  However, The custom route class overrides two functions.  SelectAction & SelectController.   When the application starts up & swagger OData starts scanning the code for endpoints, is it possible to use the custom route class to retrieve the Controller (This eliminates the need to specify the controller) and also the action (eliminates the need to specify the action).  By using reflection, is it possible to scan for function in the controller and the parameters.  These would indicate the possible routes no?   There is probably a lot of details that i'm leaving out which makes it difficult.  

Please let me know if the suggestions make sense,
Thanks,
Derek

**Comment by rbeauchamp** [comment]
Hey Derek, closing this for now. Will re-open if you want to give it a shot.
