### ISSUE TITLE
Support for other methods

### ISSUE THREAD

**Issue by codepb** [rbeauchamp/Swashbuckle.OData#5]
Hi,

Having upgraded to .Net 4.6 and added this to the project we are now trying out the documentation created. It appears this creates a standard set of operations (get, post, patch, delete). Our OData controllers never implement patch, and instead implement put. Also not all controllers implement the full range of operations. Am I missing something, or is there no way for it to discover the API methods, or to enable or disable methods such as patch and put?

**Comment by rbeauchamp-lendingtree** [comment]
Correct, at this point, it only creates a fixed set of documentation based upon the Entity Data Model. I would like this feature also and actually started working on it last night: an ODataApiExplorer similar to the [ApiExplorer](http://blogs.msdn.com/b/yaohuang1/archive/2012/05/13/asp-net-web-api-introducing-iapiexplorer-apiexplorer.aspx). I'll mark this as a feature request and include in the next release.

**Comment by rbeauchamp-lendingtree** [comment]
I think the way this will work is that the EDM will be a starting point for documentation, but the ODataApiExplorer will inspect the actual ODataControllers and constrain the final documentation output.

**Comment by joshbooker** [comment]
interesting discussion.  @rbeauchamp, any clue why ODataController explicitly disables APIExplorer?

**Comment by joshbooker** [comment]
I understand how an APIExplorer would be beneficial, but you should be able to post-modify your swagger output using IOperationFilter in Swashbuckle's SwaggerConfig.cs, No?

**Comment by rbeauchamp-lendingtree** [comment]
> any clue why ODataController explicitly disables APIExplorer

My guess from stepping through the ApiExplorer code is that:
1. OData routing is very much convention-based. (You can see this in the [OData client scaffolding](https://www.nuget.org/packages/Microsoft.OData.Client/) where a complete client is created just from the EDM model. All routes are assumed to be based on convention; there's no "API Exploring" going on there. :-) )
2. OData conventions are very different from WebApi conventions and attribute routing.
3. ApiExplorer was built against and assumes the WebApi conventions and attribute routing.

**Comment by rbeauchamp-lendingtree** [comment]
> but you should be able to post-modify your swagger output

In the current version of Swashbuckle.OData, the ODataSwaggerProvider does not apply the SwaggerDocsConfigs. The configs are being [captured](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/ODataSwaggerProvider.cs#L16), though, for application in future versions.

**Comment by Ofer-Gal** [comment]
Is there a way I can force some verbs not to show in some Entity Data Models? 
Also I Would like some custom text to appear in the docs and some custom signatures that the rout decoration and functions allow me. 
Any tutorial :-) ?

**Comment by rbeauchamp-lendingtree** [comment]
@Ofer-Gal I haven't seen a way to exclude verbs from an EDM. 

But this issue/enhancement will inspect your OData controller and determine which verbs/paths are in the actual API.

> custom text to appear in the docs and some custom signatures that the rout decoration and functions allow me

This will have to be done as another enhancement. Can you please create a GitHub issue with some detail on your requirement? Thanks.

**Comment by joshbooker** [comment]
@Ofer-Gal and this issue https://github.com/rbeauchamp/Swashbuckle.OData/issues/6 will allow you to force some paths not to show

**Comment by codepb** [comment]
Thanks, that seems to have done the trick!

**Comment by rbeauchamp-lendingtree** [comment]
Nice!

**Comment by joshbooker** [comment]
@rbeauchamp Thanks for prompt update!  Unfortunately, I don't think ODataAPIExplorer and RESTier are friendly.
I get the following exception:
500 : {"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":" at Microsoft.Restier.WebApi.Routing.RestierRoutingConvention.HasControllerForEntitySetOrSingleton(ODataPath odataPath, HttpRequestMessage request)\r\n at Microsoft.Restier.WebApi.Routing.RestierRoutingConvention.SelectController(ODataPath odataPath, HttpRequestMessage request)\r\n at Swashbuckle.OData.ODataApiExplorer.<>c__DisplayClass27_0.<GetControllerName>b__0(IODataRoutingConvention routingConvention)\r\n at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n at Swashbuckle.OData.ODataApiExplorer.GetControllerName(ODataPathRouteConstraint oDataPathRouteConstraint, ODataPath path)\r\n at Swashbuckle.OData.ODataApiExplorer.GetControllerDesciptor(ODataRoute oDataRoute, ODataPath potentialPath)\r\n at Swashbuckle.OData.ODataApiExplorer.GetApiDescription(HttpMethod httpMethod, ODataRoute oDataRoute, String potentialPathTemplate, Operation potentialOperation)\r\n at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions(ODataRoute oDataRoute, String potentialPathTemplate, PathItem potentialOperations)\r\n at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions(ODataRoute oDataRoute)\r\n at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions()\r\n at System.Lazy`1.CreateValue()\r\n at System.Lazy`1.LazyInitValue()\r\n at System.Lazy`1.get_Value()\r\n at Swashbuckle.OData.ODataApiExplorer.get_ApiDescriptions()\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"} http://localhost:57336/swagger/docs/v1

**Comment by rbeauchamp-lendingtree** [comment]
@joshbooker Hey Josh, you bet! Would you mind creating a GitHUb issue with a few pointers to how I can reproduce your issue? I haven't used RESTier yet and obviously didn't test against it. I'll setup some tests against RESTier and get it working... Thanks

**Comment by rbeauchamp-lendingtree** [comment]
Think I can I reproduce your issue by setting up the [Northwind sample](http://odata.github.io/RESTier/#01-02-Bootstrap)?

**Comment by joshbooker** [comment]
@rbeauchamp Sure, Here are the instructions:  http://odata.github.io/RESTier/#11-40-Bootstrap

Basically all you do is:
Install-Package Microsoft.RESTier -Pre
Then register in WebAPIConfig.cs

using System.Web.Http;
using NorthwindAPI.Models;
using Microsoft.Restier.EntityFramework;
using Microsoft.Restier.WebApi;
using Microsoft.Restier.WebApi.Batch;

namespace NorthwindAPI
{
    public static class WebApiConfig
    {
        public async static void Register(HttpConfiguration config)
        {
            await config.MapRestierRoute<DbApi<NorthwindContext>>(
                "Northwind",
                "Northwind/v4",
                new RestierBatchHandler(GlobalConfiguration.DefaultServer));
        }
    }
}

**Comment by rbeauchamp-lendingtree** [comment]
@joshbooker Cool. Thanks.

**Comment by joshbooker** [comment]
I think one difference over vanilla WebAPI OData is that, with RESTier, there are zero controllers in user code.  RESTier exposes OData directly from models in EF DBContext eliminating need for a controller per entity type.
