### ISSUE TITLE
Include default response schema for error handling

### ISSUE THREAD

**Issue by joshbooker** [rbeauchamp/Swashbuckle.OData#51]
I believe the original code in ODataSwaggerUitlites included a generic default response on every operation which referenced the error schema in definitions section.  Somewhere along the line this got lost.  It would be great to fix so that every operation gets something like:

```
    "responses": {
      "200": {...
      },
      "default": {
        "description": "Unexpected error",
        "schema": { "$ref": "#/definitions/_Error" }
      }
    }
```

And also include schema in the definition section something like:

```
  "definitions": {
    "_Error": { "properties": { "error": { "$ref": "#/definitions/_InError" } } },
    "_InError": {
      "properties": {
        "code": { "type": "string" },
        "message": { "type": "string" }
      }
    }
  }
```

**Comment by rbeauchamp** [comment]
Closing this old feature request as it is not important enough for someone to spend the time to implement it.
