### ISSUE TITLE
operations: consider concise summary - verbose description

### ISSUE THREAD

**Issue by joshbooker** [rbeauchamp/Swashbuckle.OData#52]
Swagger spec shows operations have both a summary and a description property.  The summary is supposed to be short and description more verbose.  Although the summary technically can be up to 120 characters, I'd suggest, for the standard operations, it should be just two words.  This will help with tooling that uses the summary as the 'friendly name' for an operation.

For example:

	"/Northwind/v4/Orders": {
	  "get": {
		"tags": [ "Orders" ],
		"summary": "Get Orders",
		"description": "Returns the EntitySet Orders",
		"operationId": "Orders_Get",
		...},
	  "post": {
		"tags": [ "Orders" ],
		"summary": "Create Order",
		"description": "Post a new entity to EntitySet Orders",
		"operationId": "Orders_Post",
		...}
	},
	"/Northwind/v4/Orders({OrderID})": {
	  "get": {
		"tags": [ "Orders" ],
		"summary": "Get Order",
		"description": "Returns the entity with the key from Orders",
		"operationId": "Orders_GetByOrderid",
		...},
	  "put": {
		"tags": [ "Orders" ],
		"summary": "Replace Order",
		"description": "Replace entity in EntitySet Orders",
		"operationId": "Orders_PutByOrderid",
		...},
	  "delete": {
		"tags": [ "Orders" ],
		"summary": "Delete Order",
		"description": "Delete entity in EntitySet Orders",
		"operationId": "Orders_DeleteByOrderid",
		...},
	  "patch": {
		"tags": [ "Orders" ],
		"summary": "Update Order",
		"description": "Update entity in EntitySet Orders",
		"operationId": "Orders_PatchByOrderid",
		...}
	},

**Comment by joshbooker** [comment]
Since this is primarily for tooling to use as 'friendly name' it's not necessary that summary value be unique.  

If you're not inclined to make this change, perhaps then please consider at least dropping 'entity in entityset' from the summary value.  Thanks again  for all your hard work!

**Comment by joshbooker** [comment]
Was able to make this change using OperationFilter like so:

    internal class ChangeSummaryInOperationFilter : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            //RENAME
            //reverse from 'Orders_Get' to 'Get Orders'
            string str = $"{string.Join(" ", operation.operationId.Split('_').Reverse())}";
            //build dict of rename replacements to be made
            string s = "Get=Get;Put=Replace;Post=Create;Delete=Delete;Patch=Update";
            var dictRename = s.Split(';').Select(x => x.Split('=')).ToDictionary(x => x[0], x => x[1]);
            //make rename replacements
            string newstr = dictRename.Aggregate(str, (current, value) => current.Replace(value.Key, value.Value));

            //SINGULARIZE
            //if has parameters other than query
            if (operation.parameters != null &! operation.parameters.All(p => p.@in == "query"))//.Any(p => p.@in == "path" || p.@in == "body"))
            {   //should prolly reuse pServ rather than new it up repeatedly(?)
                var pServ = new System.Data.Entity.Infrastructure.Pluralization.EnglishPluralizationService();
                newstr = $"{newstr.Split(' ')[0]} {pServ.Singularize(newstr.Split(' ')[1])}";
            }

            //set description and summary
            operation.description = operation.summary;
            operation.summary = newstr;
        }
    }

**Comment by rbeauchamp-lendingtree** [comment]
Woops, missed the edit. Looks like the OperationFilter meets your needs. Closing. Thanks.
