### ISSUE TITLE
Error installing package from nuget

### ISSUE THREAD

**Issue by YarmulnikA** [rbeauchamp/Swashbuckle.OData#53]
PM> Install-Package Swashbuckle.OData
Installing 'Swashbuckle.OData 2.10.1'.
Successfully installed 'Swashbuckle.OData 2.10.1'.
Adding 'Swashbuckle.OData 2.10.1' to GlobalCalendarWebApi.
Uninstalling 'Swashbuckle.OData 2.10.1'.
Successfully uninstalled 'Swashbuckle.OData 2.10.1'.
Install failed. Rolling back...
Install-Package : Could not install package 'Swashbuckle.OData 2.10.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly
 references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  Swashbuckle.OData
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by rbeauchamp-lendingtree** [comment]
Hey @YarmulnikA , yes you need to upgrade your GlobalCalendarWebApi project to .NET 4.5.2.

See https://msdn.microsoft.com/en-us/library/bb398202.aspx
