### ISSUE TITLE
Support Custom Swagger Routes with RESTier

### ISSUE THREAD

**Issue by adestis-ds** [rbeauchamp/Swashbuckle.OData#54]
Is it possible to add a custom route when using RESTier? I was not able to accomplish that... Do I have to use the CustomNavigationPropertyRoutingConvention? At the moment Operations are only created for top level entities (e.g. GET /Accounts(id) or GET /Locations(id)) but for linked entities are no operation available (e.g. I would like to see: GET /Accounts(id)/Locations)

Any hints how to accomplish that?

**Comment by bigred8982** [comment]
I have a similar need. I am using attribute routing to accomplish this.

Ex
ODataRoute("/Accounts({id})/Locations")

What I don't get is the automatic key resolution when I go this route. This
is because routes generated from the EntitySet have their parameters also
generated. So the parameter name will basically be translated into the key
name - instead of "id", it may end up as "AccountId", based in whatever the
name is in the EDM model.

So you can use the routing attribute, but you may need to accommodate for
the lack of translation by adjusting the route text and method signature to
match the key name exactly.

**Comment by rbeauchamp** [comment]
Just so I understand:
1. @adestis-ds did @bigred8982 answer your question?
2. @bigred8982 did you have a question or were you just offering a solution?
Thanks

**Comment by bigred8982** [comment]
I was attempting to offer a solution / some helpful information.

There might be a bug - or maybe just a more desired behavior - when using
the ODataRoute. I plan on doing a little more research on that topic at a
later date.

**Comment by adestis-ds** [comment]
An example how to add a custom route using RESTier would be very helpful...

DS


Am 14.01.2016 um 05:10 schrieb Richard Beauchamp <notifications@github.com<mailto:notifications@github.com>>:


Just so I understand:
1. @adestis-ds<https://github.com/adestis-ds> did @bigred8982<https://github.com/bigred8982> answer your question?
2. @bigred8982<https://github.com/bigred8982> did you have a question or were you just offering a solution?
Thanks

-

**Comment by rbeauchamp** [comment]
if I understand your basic need, it is to display related entity paths like /Accounts(id)/Locations in the Swagger UI. (without even needing an ODataRoute or Custom Route) Let's consider this a feature request: i was thinking of implementing this anyway. it would be a similar implementation to #44. let me know of I'm missing something.

**Comment by rbeauchamp** [comment]
For example, with this new feature, [this controller action](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData.Sample/ODataControllers/CustomersController.cs#L154) would show up automatically in the Swagger UI, no ODataRoute or Custom Route required.

**Comment by adestis-ds** [comment]
I'm referring explicitly to **RESTier**! There are no explicit ControllerActions, nothing to annotate. Given you have 3 entities like Account, Person, Address (and references/links defined) then accessing the root entities works out of the box and is also well documented like so:

    GET /Account(id)
    POST /Accounts
    PUT /Account(id)
    DELETE /Account(id)
    PATCH /Account(id)

    GET /Person(id)
    POST /Persons
    PUT /Person(id)
    DELETE /Person(id)
    PATCH /Person(id)

    GET /Address(id)
    POST /Addresses
    PUT /Address(id)
    DELETE /Address(id)
    PATCH /Address(id)

But other routes are also possible and depending on RoutingConventions also no special Controller actions nessecary *(as far as I understood so far)*:

    GET /Accounts(id)/Persons
    GET /Accounts(id)/Persons?$expand=Address
    GET /Accounts(id)/Person(id)?$expand=Address
    GET /Accounts(id)/Person(id)/Addresses?$count
    GET /Accounts(id)/Person(id)/Address(id)
    GET /Accounts(id)/Addresses
    GET /Accounts(id)/Address(id)

I think you get the idea. But because there are no explicit ControllerActions in my program code (using RESTier) I need a way to add these special routes manually or let the framework figure out all routes (maybe using RoutingConventions) and document them fully automatically.

I dont't know whether it works already, I'm fairly new to this topic and still investigating...

DS

**Comment by rbeauchamp** [comment]
Yes. Ok, thanks for the explanation. RESTier  is an I interesting case because it looks like the potential number of routes is large. The UI could be messy and overwhelming if swashbuckle.odata automatically displayed all possible combinations of routes. So it does sound useful for swashbuckle.odata to allow Custom Routes against RESTier so the API developer can be explicit about which routes to display. Custom Routes might already work against RESTier. I'll verify and let you know. 

Hmmm... RESTier is seeming a bit like SQL where there are many possible statements and you can't predict, of course, what the end user will want. The route is basically the JOIN clause and the query options are the SELECT and WHERE clause, etc. Maybe this was the intention of the designers...

**Comment by adestis-ds** [comment]
Yes, I completely agree... It depends from the data model what needs to be documented. I would suggest two strategies:

1. Manual routes, let the developer control what will be documented.

2. Automatic routes and optionally filter the result - e.g.:

    Remove('/entityset(key)/navigation/**')

would remove everything which is equal or longer than 3 segments.

First strategy (manual) would be most important I guess.

Dirk


Am 14.01.2016 um 13:31 schrieb Richard Beauchamp <notifications@github.com<mailto:notifications@github.com>>:


Yes. Ok, thanks for the explanation. RESTier is an I interesting case because it looks like the potential number of routes is large. The UI could be messy and overwhelming if swashbuckle.odata automatically displayed all possible combinations of routes. So it does sound useful for swashbuckle.odata to allow Custom Routes against RESTier so the API developer can be explicit about which routes to display. Custom Routes might already work against RESTier. I'll verify and let you know.

Hmmm... RESTier is seeming a bit like SQL where there are many possible statements and you can't predict, of course, what the end user will want. The route is basically the JOIN clause and the query options are the SELECT and WHERE clause, etc. Maybe this was the intention of the designers...

-

**Comment by bigred8982** [comment]
@adestis-ds I originally misunderstood your question and unintentionally changed topics. I'm sorry about that.
@rbeauchamp Your replies about OData containment were correct, and that should be a separate discussion.

**Comment by rbeauchamp-lendingtree** [comment]
@bigred8982 No problem, Thanks for trying to assist.

**Comment by rbeauchamp-lendingtree** [comment]
@adestis-ds Custom swagger routes are now supported with RESTier in v2.11.0. [Documentation has been added.](https://github.com/rbeauchamp/Swashbuckle.OData#restier) Please give it try and let me know if you find any issues. Thanks!
