### ISSUE TITLE
Exception Value cannot be null. Parameter name: baseUrl

### ISSUE THREAD

**Issue by prodrigues25** [rbeauchamp/Swashbuckle.OData#60]
Hi,

In the latest version (v.2.12.0), I get this error when opening swagger UI. In version 2.1.1 this error doesn't occur:

JavaScript runtime error: 500 : {"Message":"An error has occurred.","ExceptionMessage":"Value cannot be null.\r\nParameter name: baseUrl","ExceptionType":"System.ArgumentNullException","StackTrace":"   at Flurl.Url..ctor(String baseUrl) in c:\\Aldenteware\\Flurl\\code\\Flurl\\Url.cs:line 28\r\n   at Flurl.StringExtensions.AppendPathSegment(String url, String segment) in c:\\Aldenteware\\Flurl\\code\\Flurl\\StringExtensions.cs:line 27\r\n   at Swashbuckle.OData.Descriptions.ODataSwaggerUtilities.GetPathForEntitySet(String routePrefix, IEdmEntitySet entitySet)\r\n   at Swashbuckle.OData.Descriptions.EntityDataModelRouteGenerator.<>c__DisplayClass2_0.<GenerateEntitySetRoutes>b__0(IEdmEntitySet entitySet)\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)\r\n   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)\r\n   at Swashbuckle.OData.CollectionExtentions.AddRangeIfNotNull[T](List`1 source, IEnumerable`1 collection)\r\n   at Swashbuckle.OData.Descriptions.EntityDataModelRouteGenerator.Generate(ODataRoute oDataRoute)\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Swashbuckle.OData.CollectionExtentions.ToCollection[T](IEnumerable`1 source)\r\n   at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at System.Lazy`1.get_Value()\r\n   at Swashbuckle.OData.Descriptions.ODataApiExplorer.get_ApiDescriptions()\r\n   at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)\r\n   at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)\r\n   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken )\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"} 

I'm testing a simple Web API project with OData and hosted with OWIN.

**Comment by rbeauchamp-lendingtree** [comment]
@prodrigues25 Fix is available in v2.12.2. Please give it a try and let me know if you find any issues. Thanks!
