### ISSUE TITLE
Navigation property not automatically routed, requires custom route declaration

### ISSUE THREAD

**Issue by jondavis-ineight** [rbeauchamp/Swashbuckle.OData#61]
The OData EDM should have all the navigation properties fully disclosed for introspection, so to expose the route to a navigation property should be automatic.

We have this route.

```
    // GET: odata/AppLicenses(5)/Application
    [EnableQuery]
    public SingleResult<Application> GetApplication([FromODataUri] Guid key)
    {
        return SingleResult.Create(ConfigurationDataContext.AppLicenses.Where(m => m.AccountConfigurationID == key).Select(m => m.Application));
    }
```

In order to get this otherwise fully functional OData route to appear in Swagger, I had to make the following change.

```
    [EnableQuery]
    [ODataRoute("AppLicenses({AccountConfigurationID})/Application")]
    public SingleResult<Application> GetApplication([FromODataUri] Guid AccountConfigurationID)
    {
        return SingleResult.Create(ConfigurationDataContext.AppLicenses.Where(m => m.AccountConfigurationID == AccountConfigurationID).Select(m => m.Application));
    }
```

It would be ideal if this didn't have to be treated as a custom route.

**Comment by rbeauchamp-lendingtree** [comment]
The approach to support this feature would be similar to #44.

**Comment by jondavis-ineight** [comment]
I just want to also point out that [ODataRoute(..)] also destroys the /$count path suffix feature in Microsoft's OData v4 implementation (particularly considering /$count also measures the count of where ?$expand=..&$select=.. is used), so resolving this is going to be mandatory. I realize it's on our plate(s), just pointing out that [ODataRoute(..)] is _not_ a viable workaround.

**Comment by JamesItSolutionsLtd** [comment]
I've tried the [ODataRoute("...] WorkAround but we also have a routePrefix/{Parameter} and the parameter is not being picked up as required by swashbuckle.odata

**Comment by rbeauchamp** [comment]
Closing this old feature request as it is not important enough for someone to spend the time to implement it.

**Comment by jondavis-ineight** [comment]
I was not aware that there was some kind of time frame for which a requested feature needs to be implemented. I suppose if I end up getting to this I'll create a new feature request.
