### ISSUE TITLE
Should display query string parameters not described by the EDM model or in the ODataRoute

### ISSUE THREAD

**Issue by jondavis-ineight** [rbeauchamp/Swashbuckle.OData#62]
Given this example ..

	[EnableQuery]
	[ODataRoute("Foobars")]
	public IQueryable<Foobar> GetFoobars(bool bar)
	{
		IEnumerable<Foobar> foobars = new[]
		{
			new Foobar { Id=1, Variation = "a"},
			new Foobar { Id=2, Variation = "b"},
			new Foobar { Id=3, Variation = "c"},
			new Foobar { Id=4, Variation = "d"}
		};
		if (bar == true) foobars = foobars.Where(fb => fb.Id >= 3);
		return foobars.AsQueryable();
	}

.. if I change `bool bar` to `[FromODataUri] bool? bar = null` the parameter drops off completely from Swagger UI. I tried also updating `[ODataRoute(..)]` with `[ODataRoute("Foobars?bar={bar:bool?}")]`. I don't know if this is a missing feature (or bug) or if there's something I can do to make the parameter reappear. I'm not particularly concerned if, given whatever change I would make to get it to reappear, Swagger UI would still a true/false option here, I'd rather Swagger force an option than it not show the parameter at all, but I won't be able to make this parameter non-nullable outside of Swagger.

If I were to assume I'm doing it wrong, what am I missing? If it's a missing feature, any clue which class to get started poking at?

**Comment by rbeauchamp-lendingtree** [comment]
@jondavis-ineight Can you please provide a sample ODataConfig for this? I.e., your MapODataServiceRoute() call and ODataConventionModelBuilder configuration?

**Comment by jondavis-ineight** [comment]
It's just 

    var builder = new ODataConventionModelBuilder { Namespace = "Default" };
    builder.EntitySet<Foobar>("Foobars");
    config.MapODataServiceRoute("odata", "odata", builder.GetEdmModel());

**Comment by rbeauchamp-lendingtree** [comment]
Researching...

**Comment by bigred8982** [comment]
Just curious, but wouldn't that end up being two separate routes? Following
the standard conventions set out by the convention model builder and
examples from Microsoft, shouldn't you have two methods on your controller?
One that takes zero parameters, and one that takes a key?

It seems like that would be the "correct" approach.

In your case, wouldn't it be better to simply set a parameter like this in
the query string?

**Comment by rbeauchamp-lendingtree** [comment]
Hey @jondavis-ineight Fix for this issue is available in v2.12.5. Give it a try and let me know if you find any issues. Thanks!

**Comment by jondavis-ineight** [comment]
So sorry I haven't had the chance to respond sooner. This is awesome, thanks! I'll take a look at this soon!

**Comment by jondavis-ineight** [comment]
That seems to work. Thanks!
