### ISSUE TITLE
OData query parameters should be limited to $expand and $select for APIs that return a single result

### ISSUE THREAD

**Issue by aoa241175** [rbeauchamp/Swashbuckle.OData#64]
I have this scenary:

### Model
```
public class ToolHistory
{
        [Key] 
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
}
```

### ODataModel
```
var builder = new ODataConventionModelBuilder()
builder.EntitySet<ToolHistory>("ToolHistories");
var model = builder.GetEdmModel();
var edmEntityType = model.FindType(namespace + "ToolHistory") as IEdmEntityType;
var edmProperty = edmEntityType.FindProperty("Code");
(model as EdmModel).AddAlternateKeyAnnotation(edmEntityType, new Dictionary<string, IEdmProperty>
{
	{"Code", edmProperty}
});
```

### Controller
This actions allow get item by key and by code. 
```
public class ToolHistoriesController : ODataController
{
        [EnableQuery]
        public IHttpActionResult Get([FromODataUri] int key)
        {
            throw new NotImplementedException();
        }

        [EnableQuery]
        [ODataRoute("ToolHistories(Code={code})")]
        public IHttpActionResult Get([FromODataUri] string code)
        {
            throw new NotImplementedException();
        }
}
```
If I add the [ODataRoute("ToolHistories(Code={code})")], the metadata is generate through **AttributeRouteStrategy**, but add all query parameters because I add **EnableQuery** attribute which is incorrect.I think that you should only add $expand and $select.

If I missing the odataroute attribute, the metadata for this action is not generated. There is another way for do this, maybe a SwaggerRoute Attribute?

attach a image

![path with annotation](https://cloud.githubusercontent.com/assets/11401096/12775354/d559b44e-ca12-11e5-82a0-62db67a74caf.jpg)

**Comment by bigred8982** [comment]
Have you tried annotating your route with a response type?

[ResponseType(typeof(ToolHistory))]

**Comment by aoa241175** [comment]
Yes, I did and the result is same.

**Comment by bigred8982** [comment]
I went ahead and created a sample for this specific issue.

https://github.com/bigred8982/Swashbuckle.OData/tree/issue_64_sample

**Comment by rbeauchamp-lendingtree** [comment]
@aoa241175 and @bigred8982 Thanks both for providing example code along with attached images. I'll take a look after #57, unless you guys get this working yourselves. PRs are welcome. ;-)

**Comment by rbeauchamp-lendingtree** [comment]
@aoa241175  Let me summarize the issue as I understand it, written in the form of a requirement:

"If an API returns a single instance, then the default, displayed OData query parameters should be limited to $expand and $select"

Does this look correct?

**Comment by bigred8982** [comment]
I agree with that statement.

I took a cursory glance and this is coming from the call to ```CreateSwaggerPathForEntitySet```. 

I believe the correct fix would be to analyze the return type to determine if the route is processing a single entity or a set. In this specific case, we would need to fall back to the ReponseType attribute since IHttpActionResult is not descriptive enough. I'm thinking that checking if the type implements ```IQueryable``` or ```IEnumerable``` then it should be counted as a set.

I haven't had time to dig around to see where best to put this logic yet, but I can probably make some time this weekend if you haven't beaten me to the punch by then.

**Comment by aoa241175** [comment]
@rbeauchamp-lendingtree Yes,is correct

> "If an API returns a single instance and the action has the [EnableQuery] attribute, then the default, displayed OData query parameters should be limited to $expand and $select".

And this is correctly display for the next case:
```
[EnableQuery]
public IHttpActionResult Get([FromODataUri] int key)
{
   throw new NotImplementedException();
}
```
But the case to which I refer is when I use the ODataRouteAttribute
```
[EnableQuery]
[ODataRoute("ToolHistories(Code={code})")]
public IHttpActionResult Get([FromODataUri] string code)
{
   throw new NotImplementedException();
}
```
I need use the odataRouteAttribute because I will use a custom route to get a item through Code property, that its a alternate key for my entity.
I need use the odataRouteAttribute because I will use a custom route to get a item through Code property, that its a alternate key for my entity.

**Comment by rbeauchamp-lendingtree** [comment]
@aoa241175 Thanks, understood.

**Comment by rbeauchamp-lendingtree** [comment]
I think the [EnableQueryFilter](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/EnableQueryFilter.cs) could be modified to do an extra check against ResponseType attribute, determining whether the response type is a collection or not.

A helper method for this check [is available](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/Descriptions/TypeHelper.cs#L40).

**Comment by rbeauchamp-lendingtree** [comment]
If either of you do implement this, I would ask that you also please provide a unit test such as [this](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData.Tests/Fixtures/EnableQueryTests.cs#L25).

**Comment by rbeauchamp** [comment]
While we're at it, we should probably only display [EnableQuery.AllowedQueryOptions](https://msdn.microsoft.com/en-us/library/system.web.odata.enablequeryattribute.allowedqueryoptions(v=vs.118).aspx#P:System.Web.OData.EnableQueryAttribute.AllowedQueryOptions).

**Comment by bigred8982** [comment]
Oh yes, great idea!

**Comment by bigred8982** [comment]
Go ahead and assign this one to me.

**Comment by rbeauchamp** [comment]
looks like issues can only be assigned to users with push access to the repo. I'll mark it as assigned. thx.

**Comment by bigred8982** [comment]
Created pull request #65

**Comment by rbeauchamp-lendingtree** [comment]
@aoa241175 Feature is available in v2.15.0.

Thanks @bigred8982 for implementing this!

**Comment by aoa241175** [comment]
Excellent!!!

**Comment by sebekz** [comment]
I think right now it's too strict, since 

`[ResponseType(typeof(IQueryable(Employee)))]` 

is required and it does not take into the consideration, that one may also use something like 

`[SwaggerResponse(HttpStatusCode.OK, "OK", typeof(IQueryable<Employee>))]`

Right now for all OData parameters to be included in the Swagger doc I have to use both attributes and `[ResponseType]` is redundant when `[SwaggerResponse]` is used.

Please correct me if I am wrong.

**Comment by rbeauchamp** [comment]
@sebekz if you have a fix for the issue you've identified we'd appreciate a pull request.
