### ISSUE TITLE
Custom Attribute Route implementation

### ISSUE THREAD

**Issue by ChivanTiebosch** [rbeauchamp/Swashbuckle.OData#69]
The method GetODataActionDescriptorsFromAttributeRoutes in Swashbuckle.OData.Descriptions uses the Reflection Helper to get the field  _attributeMappings form the Attribute Routing convention. If you create a custom implementation of AttributeRoutingConvention, for instance to override ShouldMapController this results in a error in the Reflection Helper. This because the fact that the field that is looked up could be a field of one of the base classes is not taken into account. This could be fixed by checking if the base class of the incoming object contains the requested field if the first lookup fails in the GetInstanceField method of the reflection helpers. I would be very grateful if this could be implemented.

**Comment by rbeauchamp-lendingtree** [comment]
Hey @ChivanTiebosch, thanks for creating this issue. It is fixed in v2.16.1. Give it a try and let me know if you find any issues.

**Comment by ChivanTiebosch** [comment]
Works like a charm. Thanks for the swift fix.
