### ISSUE TITLE
Installation issue?

### ISSUE THREAD

**Issue by darewreck54** [rbeauchamp/Swashbuckle.OData#7]
HI,

I tried to install the package, but get the following issue?  Any idea of how to resolve it?

PM> Install-Package Swashbuckle.OData
Installing 'Swashbuckle.OData 2.0.0'.
Successfully installed 'Swashbuckle.OData 2.0.0'.
Adding 'Swashbuckle.OData 2.0.0' to Swagger.
Uninstalling 'Swashbuckle.OData 2.0.0'.
Successfully uninstalled 'Swashbuckle.OData 2.0.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'Swashbuckle.OData 2.0.0'. You are 
trying to install this package into a project that targets 
'.NETFramework,Version=v4.5', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Install-Package Swashbuckle.OData
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOper 
   ationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.C 
   ommands.InstallPackageCommand

**Comment by rbeauchamp** [comment]
Hey, it looks like your visual studio project may be targeting .net 4.5. But this NuGet package requires that you target .net 4.5.2.
