### ISSUE TITLE
Enhancement: Custom parameters should precede OData parameters

### ISSUE THREAD

**Issue by jondavis-ineight** [rbeauchamp/Swashbuckle.OData#75]
Currently the custom parameters in a route are getting appended to the parameters list after the OData parameters ($expand, $filter, etc). Since custom parameters are of higher priority for consuming a route than OData querystring parameters, the custom parameters should appear at the top of the list.

It is not alphabetically sorted (and shouldn't be). I made a tweak to make this work but it broke other things so unfortunately I don't know where/how best to tackle this.

**Comment by rbeauchamp** [comment]
Good idea, I'll check out after some bug fix issues.

**Comment by rbeauchamp** [comment]
Closing this old feature request as it is not important enough for someone to spend the time to implement it.

**Comment by jondavis-ineight** [comment]
I was not aware that there was some kind of time frame for which a requested feature needs to be implemented. I suppose if I end up getting to this I'll create a new feature request.

**Comment by rbeauchamp** [comment]
i'd rather maintain a list of relevant issues that people are discussing and/or working on. i don't want requests hanging around for more than a year that no one is willing to implement. if you decide to work on this, feel free to re-open it.
