### ISSUE TITLE
Using with WCF DataServices<T> OData service?

### ISSUE THREAD

**Issue by neilhosey** [rbeauchamp/Swashbuckle.OData#78]
Hi,

Is it possible to use this with  WCF DataServices<T> OData service?

Thanks
Neil

**Comment by rbeauchamp** [comment]
Hi Neil, I'm not familiar with such a service and have never used it; I'm not sure! Any chance you could give it a try in your project and let us know?

**Comment by neilhosey** [comment]
Hi Richard,

Thanks for the reply!  

It is from the WCF Data Services API:
https://msdn.microsoft.com/en-us/data/odata.aspx
,
So instead of using a web API controller or ODAtaController I want to try use this DataService<T> where T is my EF DbContext.  

Would you be able to point me in the right direction where I could add a new impl to handle this different type of service?

Thanks
Neil

**Comment by rbeauchamp** [comment]
That's a tough one. I haven't factored out variability across odata service types because there hasn't been much variability. so there's no "plug in" point for new service types. you'll be breaking new ground if you want to develop WCF odata support.

**Comment by neilhosey** [comment]
doh!  thats a pity!

I'll have to have a look and see if theres value in doing this.

Thanks for the responses!
Neil
