### ISSUE TITLE
Internal Server Error (500) when using Serializable Attribute

### ISSUE THREAD

**Issue by bradm1** [rbeauchamp/Swashbuckle.OData#79]
When using the **[Serializable]** attribute on the OData Model it causes the 500 error:

_500 : {"Message":"An error has occurred.","ExceptionMessage":"Precondition failed: currentProperty != null","ExceptionType":"System.Diagnostics.Contracts.__ContractsRuntime+ContractException","StackTrace":" at ...._

**Comment by YarmulnikA** [comment]
Any ideas on when this will get fixed?
Thanks.

**Comment by rbeauchamp-lendingtree** [comment]
@YarmulnikA  No, I currently don't have plans and it's not assigned. Can you take it on?

**Comment by YarmulnikA** [comment]
The problem was resolved after I put this line in WebApiConfig file
config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new DefaultContractResolver { IgnoreSerializableAttribute = true };

**Comment by rbeauchamp** [comment]
ok. thanks for the heads up.

**Comment by rbeauchamp** [comment]
Closing this as there seems to be a resolution.
