### ISSUE TITLE
[ApiExplorerSettings(IgnoreApi = true)] is not honoured, Can't hide unwanted controllers & APIs

### ISSUE THREAD

**Issue by PratikDeb** [rbeauchamp/Swashbuckle.OData#80]
Swagger used to honor "[ApiExplorerSettings(IgnoreApi = true)]" for hiding non public controllers for webapi 2, For Odata, looks like this is not honored. How do I hide unwanted controllers & APIs ?

**Comment by rbeauchamp** [comment]
At this point there is no such attribute or configuration. In fact, Swashbuckle.OData explicitly ignores the APIExplorerSettings attribute; it has its own APIExplorer. Maybe we need an ODataAPIExplorerSettings attribute?
