### ISSUE TITLE
Document ODataActionParameters Model Schema

### ISSUE THREAD

**Issue by arcanelore** [rbeauchamp/Swashbuckle.OData#81]
How can I document the Json Model Schema that a method is expecting to be passed in via the ODataActionParameters type?

I have not be able to figure out/find a way to do this.

![odataactionparametersquestion](https://cloud.githubusercontent.com/assets/13991366/13854917/1b8f623a-ec2b-11e5-893b-cf976bb5debb.png)

**Comment by rbeauchamp-lendingtree** [comment]
Hey @arcanelore, need to research this. Will let you know.

**Comment by arcanelore** [comment]
@rbeauchamp  Thanks for the update.

**Comment by ChrisSchaller** [comment]
Currently normal xml doc comments for your ODataActionParameter will come through as long as you declare the ODataActionParameter as a formal parameter to your action method.
![odataactionparameter swagger with comments](https://cloud.githubusercontent.com/assets/7519539/15732876/ff417200-28c3-11e6-8d99-fdb3dde01da8.PNG)

Another hack we really like is not show this parameter in the Swagger at all if our action does not have any parameters, currently you can do this with an OperationFilter:
![odataactionparamter omitted from swagger if undefined](https://cloud.githubusercontent.com/assets/7519539/15732916/3bd64f88-28c4-11e6-922c-e7ae5143a2f7.PNG)

Code:

[Swagger Comments for ODataParameters.txt](https://github.com/rbeauchamp/Swashbuckle.OData/files/294762/Swagger.Comments.for.ODataParameters.txt)

**Comment by rbeauchamp** [comment]
Closing this as there seems to be an answer. Will re-open if not sufficient.
