### ISSUE TITLE
Target ASP.NET Core

### ISSUE THREAD

**Issue by neoaisac** [rbeauchamp/Swashbuckle.OData#82]
Swashbuckle.OData NuGet package currently (v2.17.1) is targetted to .NetFramework,Version=v4.5.2 only. This prevents its usage in projects targeting the new ASP.NET Core.

**Comment by rbeauchamp** [comment]
Won't be able to implement this until MS implements OData support in .net core. See OData/odata.net#568

**Comment by malichishti** [comment]
@rbeauchamp looks like MS has added support for OData libs.

**Comment by rbeauchamp** [comment]
@malichishti Does ASP.NET core support OData?

**Comment by alexandra-olteanu** [comment]
@rbeauchamp https://www.nuget.org/packages/Microsoft.AspNetCore.OData/

**Comment by Behnam-Emamian** [comment]
OData for asp.net core is ready now, it is possible to make it?
