### ISSUE TITLE
OData V3 libraries

### ISSUE THREAD

**Issue by wasphub** [rbeauchamp/Swashbuckle.OData#90]
@rbeauchamp-lendingtree  As logical, this implementation uses the latest OData libraries (V4), but for internal reasons we need to stick with the V3 libraries. If I had to fork this and back-port it, would you say it's something like "wow, good luck!" or should it be relatively simple? I do not have much resources to embark in something that gets too big without knowing in advance...

Thx

**Comment by rbeauchamp-lendingtree** [comment]
AFAIK, it would be tough because v4 is so different that v3. Don't even think it would work on your machine.

**Comment by wasphub** [comment]
Ok, thanks for the advice and for your contribution :)
