### ISSUE TITLE
Flurl 2.0 incompatibility

### ISSUE THREAD

**Issue by wmalgadey** [rbeauchamp/Swashbuckle.OData#91]
Maybe you should include a max-version in your nuget-Packet. The current version 2.0 of the flurl-package is not compatible with Swashbuckle.OData.

**Comment by rbeauchamp-lendingtree** [comment]
@wmalgadey Thanks! Constraint is now defined in https://www.nuget.org/packages/Swashbuckle.OData/2.18.2

**Comment by wmalgadey** [comment]
greate. Thanks :+1:

**Comment by glyons** [comment]
Is possible to use Flurl 2.2.1  ?  I've downloaded the source and compile it using Flurl 2.2.1. The sample site loads up without error. 

However on my own project which I like to use Flurl 2.2.1 for support of Flurl.http in my tests.  I receive the following message on the Swagger site

500 : {"$id":"1","Message":"An error has occurred.","ExceptionMessage":"Method not found: 'Flurl.Url Flurl.StringExtensions.AppendPathSegment(System.String, System.Object)'.","ExceptionType":"System.MissingMethodException","StackTrace":" at Swashbuckle.OData.Descriptions.SwaggerRoute.get_PrefixedTemplate()\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.CreateHttpRequestMessage(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig) in C:\\DEV\\Projects\\Swashbuckle.OData\\Swashbuckle.OData\\Descriptions\\SwaggerRouteStrategy.cs:line 89\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig) in C:\\DEV\\Projects\\Swashbuckle.OData\\Swashbuckle.OData\\Descriptions\\SwaggerRouteStrategy.cs:line 66\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig) in C:\\DEV\\Projects\\Swashbuckle.OData\\Swashbuckle.OData\\Descriptions\\SwaggerRouteStrategy.cs:line 51\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions() in C:\\DEV\\Projects\\Swashbuckle.OData\\Swashbuckle.OData\\Descriptions\\ODataApiExplorer.cs:line 43\r\n at System.Lazy`1.CreateValue()\r\n at System.Lazy`1.LazyInitValue()\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion) in C:\\DEV\\Projects\\Swashbuckle.OData\\Swashbuckle.OData\\ODataSwaggerProvider.cs:line 308\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion) in C:\\DEV\\Projects\\Swashbuckle.OData\\Swashbuckle.OData\\ODataSwaggerProvider.cs:line 65\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at Util.MicroServices.WebAPI.Extensions.APILogHandler.<>n__FabricatedMethod8(HttpRequestMessage , CancellationToken )\r\n at Util.MicroServices.WebAPI.Extensions.APILogHandler.<SendAsync>d__5.MoveNext() in c:\\DEV\\Projects\\Backstage\\MicroServices\\Util.MicroServices\\WebAPI\\Extensions\\ApiLogHandler.cs:line 36\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"} http://localhost/detego.Service.Outbound/swagger/docs/v1 

Thanks

**Comment by rbeauchamp-lendingtree** [comment]
No you can't use Flurl 2+ at this time as they made backwards incompatible changes to their code.

**Comment by glyons** [comment]
Would be practical to support the newer version. As I use FlUrl.Http Package to Test WebAPI interfaces in our Test Projects as proper Unit Test. (The FlUrl.Http depends on FlUrl 2.2.1 or higher.)

**Comment by rbeauchamp-lendingtree** [comment]
@glyons Would you be able to submit a pull request that updates Flurl to 2+?

**Comment by patrickmichalina** [comment]
Waiting for a PR to this?

**Comment by icnocop** [comment]
When I had Flurl 0.1.0 installed, I received the following error"
```
500: {
    "Message": "An error has occurred.",
    "ExceptionMessage": "Could not load file or assembly 'Flurl, Version=1.1.2.0, Culture=neutral, PublicKeyToken=6fcef7ff3cf26ca5' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
    "ExceptionType": "System.IO.FileLoadException",
    "StackTrace": " at Swashbuckle.OData.Descriptions.SwaggerRoute.get_PrefixedTemplate()\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.CreateHttpRequestMessage(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.<>c__DisplayClass3_0.<Generate>b__1(SwaggerRoute potentialSwaggerRoute)\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n at Swashbuckle.OData.CollectionExtentions.ToCollection[T](IEnumerable`1 source)\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions()\r\n at System.Lazy`1.CreateValue()\r\n at System.Lazy`1.LazyInitValue()\r\n at System.Lazy`1.get_Value()\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.get_ApiDescriptions()\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken )\r\n at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
}
http: //localhost:80/WebApplication1/swagger/docs/v1
```
So it seems Swashbuckle.OData currently needs at least Flurl 1.1.2, if not specifically.

**Comment by rbeauchamp** [comment]
Fixed in https://github.com/rbeauchamp/Swashbuckle.OData/releases/tag/v3.2.0. NuGet package: https://www.nuget.org/packages/Swashbuckle.OData/3.2.0 Thanks @cibergarri!
