### ISSUE TITLE
OData in Standard ApiController Routes

### ISSUE THREAD

**Issue by jayoungers** [rbeauchamp/Swashbuckle.OData#94]
I initially installed Swashbuckle last year and noticed it didn't handle our OData end points all that well, but it wasn't a big issue.  Recently we've gotten more demand for using the API/documentation, so when I went to see if there was a way to fix the issue I was happy to see this project is out here!

My question is our end points are not standard `ODataController`s, they're custom `ApiController `API end points: we do this because we want the power of being able to query, but with the ability to add our own custom rules on top of that query as well as return the data in a more friendly format (viewmodels).

So our endpoints end up looking like this:

```
[HttpGet, Route("")]
[System.Web.Http.Description.ResponseType(typeof(List<MyEntityViewModel>))]
public virtual HttpResponseMessage Get(ODataQueryOptions<Data.MyEntity> query, bool someFlag = false)
{
    return BusinessLogic(query.ApplyTo, someFlag);
}
```

From the documentation I wasn't entirely sure the correct way of setting this up.  I was hoping it would pick up any reference to `ODataQueryOptions<T>` and generate based upon that, but it looks like what I need to do is setup custom `AddCustomSwaggerRoute`s, is that correct?

Thanks in advance! (and thanks for creating this in general - very clean and easy swagger implementation)

**Comment by rbeauchamp-lendingtree** [comment]
Hey @jayoungers, interesting integration of OData with ApiControllers. You are entering new ground with this combination. I don't have a quick answer; you'll have to experiment and see what works.

Currently there is a sharp division of functionality between ODataControllers/OData and ApiControllers/WebApi. Swashbuckle.OData explicitly handles OData routes, not WebApi routes.

Would be nice if you can post your results here if you get something working!

**Comment by jayoungers** [comment]
After getting in the weeds a bit with your project and Swashbuckle, I just pulled out the applicable parameters for my project from yours and added it to an operation filter:

```
public class ODataOperationFilter : IOperationFilter
{
    public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
    {
        if (apiDescription.ParameterDescriptions.Select(p => p.ParameterDescriptor.ParameterType).Any(t => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(System.Web.OData.Query.ODataQueryOptions<>)))
        {
            operation.parameters.Add(new Parameter() { name = "$filter", @in = "query", description = "Filters the results, based on a Boolean condition.", type = "string", required = false });
            operation.parameters.Add(new Parameter() { name = "$orderby", @in = "query", description = "Sorts the results.", type = "string", required = false });
            operation.parameters.Add(new Parameter() { name = "$top", @in = "query", description = "Returns only the first n results.", type = "integer", required = false });
            operation.parameters.Add(new Parameter() { name = "$skip", @in = "query", description = "Skips the first n results.", type = "integer", required = false });
            operation.parameters.Add(new Parameter() { name = "$count", @in = "query", description = "Includes a count of the matching results in the odata-count header.", type = "boolean", required = false });
        }
    }
}
```

I don't like how the UI encodes the '$' at the beginning of the parameter names, but it seems like everything's working ok.

Thanks again!

**Comment by rbeauchamp-lendingtree** [comment]
Cool. Thanks for posting your operation filter!
