### ISSUE TITLE
Problem using DataContractAttribute with modified name

### ISSUE THREAD

**Issue by OwenMadden** [rbeauchamp/Swashbuckle.OData#98]
This seems to be a similar issue to #95 , but causes a different exception.

When using the DataContractAttribute with a modified name an exception occurs:

> System.Exception : ResponseContent: {"message":"An error has occurred.","exceptionMessage":"Sequence contains no matching element","exceptionType":"System.InvalidOperationException","stackTrace":"   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at System.Web.OData.TypeHelper.FindType(String fullName) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\Descriptions\TypeHelper.cs:line 236\r\n   at Swashbuckle.OData.SchemaExtensions.GetReferencedType(Schema schema) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\SchemaExtensions.cs:line 18\r\n   at Swashbuckle.OData.SchemaRegistryExtensions.RegisterReferencedTypes(SchemaRegistry registry, IEdmModel edmModel, Schema schema) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\SchemaRegistryExtensions.cs:line 46\r\n   at Swashbuckle.OData.SchemaRegistryExtensions.RegisterReferencedTypes(SchemaRegistry registry, IEdmModel edmModel, Schema schema) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\SchemaRegistryExtensions.cs:line 60\r\n   at Swashbuckle.OData.SchemaRegistryExtensions.GetOrRegisterParameterType(SchemaRegistry registry, IEdmModel edmModel, HttpParameterDescriptor parameterDescriptor) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\SchemaRegistryExtensions.cs:line 25\r\n   at Swashbuckle.OData.ODataSwaggerProvider.CreateParameter(SwaggerApiParameterDescription paramDesc, Boolean inPath, SchemaRegistry schemaRegistry, IEdmModel edmModel) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 272\r\n   at Swashbuckle.OData.ODataSwaggerProvider.<>c__DisplayClass7_0.<CreateOperation>b__0(ApiParameterDescription paramDesc) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 190\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Swashbuckle.OData.ODataSwaggerProvider.CreateOperation(ApiDescription apiDescription, SchemaRegistry schemaRegistry) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 185\r\n   at Swashbuckle.OData.ODataSwaggerProvider.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry) in C:\\New folder (2)\\Swashbuckle.OData\\Swashbuckle.OData\\ODataSwaggerProvider.cs:line 159\r\n   at Swashbuckle.OData.ODataSwaggerProvider.<>c__DisplayClass4_0.<GetSwagger>b__3(IGrouping`2 group) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 72\r\n   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)\r\n   at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion) in C:\New folder (2)\Swashbuckle.OData\Swashbuckle.OData\ODataSwaggerProvider.cs:line 68\r\n   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"}
> Response: StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
> {
>   Date: Thu, 04 Aug 2016 11:13:21 GMT
>   Server: Microsoft-HTTPAPI/2.0
>   Content-Length: 3693
>   Content-Type: application/json; charset=utf-8
> }
> Request: Method: GET, RequestUri: 'http://localhost:8347/swagger/docs/v1', Version: 1.1, Content: <null>, Headers:
> {
>   Accept: application/json
> }
>    at Swashbuckle.OData.Tests.HttpExtensions.<ValidateSuccessAsync>d__12.MoveNext() in HttpExtensions.cs: line 278
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Swashbuckle.OData.Tests.HttpExtensions.<GetJsonAsync>d__2`1.MoveNext() in HttpExtensions.cs: line 56
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Swashbuckle.OData.Tests.ActionTests.<It_supports_actions_against_an_entity>d__3.MoveNext() in ActionTests.cs: line 185
>    at NUnit.Framework.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
>    at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()

For example, I applied the DataContractAttribute with a modified name on the SupplierDto type in the ActionTests:

```
[DataContract(Name="ASupplier")]
    public class SupplierDto
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
```

Running any of the ActionTests should then recreate the problem. I looked in the TypeHelper class and it seems that we are looking for a type with FullName "Swashbuckle.OData.Tests.ASupplier" which of course we can not find.

**Comment by 0xced** [comment]
I stumbled on the same exception but the cause was different: all my entities were defined as `protected`. By changing them to `public`, the exception went away.
